### ISSUE TITLE
[Proposal] Create a VSCode package

### ISSUE THREAD

**Issue by abdonrd** [file-icons/atom#462]
It would be great to have this package in VSCode.

**Comment by Alhadis** [comment]
I've never used VSCode, so, not sure I can be of much help there...

**Comment by abdonrd** [comment]
Wow! Thanks for the quick response!

What a shame! I'm testing VSCode these days and I miss this package.

**Comment by Alhadis** [comment]
You'll miss it even more in a few weeks once V2 is released, unless VSCode has hashbang detection, heh.

Paging @ihodev and @nfantone, as they may be interested in this.

**Comment by nfantone** [comment]
@abdonrd My feelings exactly when switching to VSCode. I opened #422 in the past and tried to put together something similar for that editor, but failed miserably at the time. At present, VSCode does not support styling the workbench or CSS/font icons. But it's [coming along](https://github.com/Microsoft/vscode/issues/3112#issuecomment-263438933)!

**Comment by Alhadis** [comment]
Well, the SVG source for the package's custom icon-font is [available here](https://github.com/Alhadis/FileIcons). =) Not sure if that'll help you in your endeavours, but everything's there.

**Comment by abdonrd** [comment]
@nfantone the VSCode 1.5 add support for icons: https://code.visualstudio.com/blogs/2016/09/08/icon-themes#_file-icon-themes

**Comment by abdonrd** [comment]
I will add the VSCode examples:
- With SVG: [theme-defaults/fileicons](https://github.com/Microsoft/vscode/tree/master/extensions/theme-defaults/fileicons)
- With fonts: [theme-seti/icons](https://github.com/Microsoft/vscode/tree/master/extensions/theme-seti/icons)

**Comment by gluons** [comment]
@abdonrd Have you try [vscode-icons](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons)?

It do exactly as Atom [file-icons](https://atom.io/packages/file-icons).

**Comment by abdonrd** [comment]
@gluons those icons are different. 😕

**Comment by gluons** [comment]
@abdonrd OK. You prefer this icon styles. (me too)
If **file-icons** has been ported to VSCode, I'll use it too. 😃

**Comment by DanBrooker** [comment]
Whipped up a quick VSCode extension: https://github.com/file-icons/vscode using the same definitions and icons

**Comment by abdonrd** [comment]
@DanBrooker thank you very much! 🎉

I see some differences:

Atom vs VSCode:

<img width="184" alt="screen shot 2017-01-03 at 11 22 00" src="https://cloud.githubusercontent.com/assets/1007051/21605102/31349652-d1a7-11e6-9879-b73f1af2547c.png"> <img width="192" alt="screen shot 2017-01-03 at 11 22 08" src="https://cloud.githubusercontent.com/assets/1007051/21605104/3533d786-d1a7-11e6-8de1-396b6e02f0db.png">

And the icons are not centered with the same size.

**Comment by DanBrooker** [comment]
Theres a little less control in VSCode with regard to what the icon extension can do, @abdonrd open an issue here https://github.com/file-icons/vscode/issues anyway

**Comment by abdonrd** [comment]
Closed by https://github.com/file-icons/vscode! :)

**Comment by nfantone** [comment]
This is great news.
