### ISSUE TITLE
Failed to move file with split window

### ISSUE THREAD

**Issue by carrodher** [file-icons/atom#485]
I have a split window if I move the file between splits (dragging the header containing the name and icon), the icon disappears at the destination.

![screen shot 2017-01-03 at 11 44 59](https://cloud.githubusercontent.com/assets/13216600/21607143/72955b4c-d1b4-11e6-90f3-a52c2687ae2f.png)

**Comment by Alhadis** [comment]
Hi @carrodher, does this still happen after installing `file-icons` v2.0.5?

**Comment by carrodher** [comment]
Hi, the problem appears with 2.0.4. Now, I just updated to 2.06 and it is working fine. Thanks!
