### ISSUE TITLE
Icons not showing in file tabs

### ISSUE THREAD

**Issue by PetrKaleta** [file-icons/atom#495]
System: `Mac OS X 10.12.2`
Atom: `1.12.8`
file-icons: `2.0.6`

**Comment by Alhadis** [comment]
Screenshot, please.

**Comment by PetrKaleta** [comment]
![screen shot 2017-01-04 at 10 19 37](https://cloud.githubusercontent.com/assets/282588/21637483/56d0e54e-d267-11e6-86d7-763a9b04535a.png)

**Comment by PetrKaleta** [comment]
Theme is official Atom One Dark UI

**Comment by Alhadis** [comment]
1. Are there errors listed in the dev-console? Check:<br/>
<kbd>**View** menu</kbd> → <kbd>Developer</kbd> → <kbd>Toggle Developer Tools</kbd> and click <kbd>Console</kbd>

2. Open the settings page for the `Tabs` package, and make sure this setting is checked:<br/><br/><img src="https://cloud.githubusercontent.com/assets/2346707/21637666/1336236c-d2bc-11e6-92dc-eef92686a568.png" width="379" alt="Figure 1" />

3. Have you just recently installed an upgrade? If so, you may need to reload the window to clear traces of the old package.

**Comment by PetrKaleta** [comment]
Ha, sorry for that. For some reason Show Icons option was disabled in Tabs package.
