### ISSUE TITLE
Problem when work with Remote-FTP

### ISSUE THREAD

**Issue by NoMad42** [file-icons/atom#507]
I have problem after last update when work with remote files via [Remote-FTP](https://atom.io/packages/Remote-FTP) package.
![2017-01-09_10-45](https://cloud.githubusercontent.com/assets/19962558/21759889/eebfb840-d658-11e6-94b2-580d2b89e105.jpg)

**Comment by Alhadis** [comment]
Duplicate of #486. Please refer to that issue for updates.
