### ISSUE TITLE
Icon of a repository is missing

### ISSUE THREAD

**Issue by hellfish2** [file-icons/atom#513]
Hi, When i get an update the icon file of a repository on git are missing, the solution i found was disable the package file-icons and enable again. Problem solved :confused:

**Comment by Alhadis** [comment]
Can you post a screenshot?

**Comment by hellfish2** [comment]
Yes i can, but when it happens again because i cannot reproduce this issue without getting a update!

**Comment by Alhadis** [comment]
Bien. Closing this for now; please post a screenshot here if this happens again. Gracias.
