### ISSUE TITLE
Not able to update package 

### ISSUE THREAD

**Issue by MandarSant** [file-icons/atom#515]
I have installed atom on windows 8.1 but when i tried to update package it  and  is not updating when click on update button the process continues and after sometime I got following error each time when i update 

![capture](https://cloud.githubusercontent.com/assets/20091634/21933232/8e3e040c-d9ca-11e6-8cce-c299f66ab815.JPG)

**Comment by Alhadis** [comment]
@MandarSant Double-check you have write-access to the destination directory where you're installing the package.

**Comment by MandarSant** [comment]
@Alhadis  yes i have write-access my other packages are successfully updating

**Comment by Alhadis** [comment]
Try this:

1. Close Atom
2. Manually delete `C:\Users\mandar\.atom\packages\file-icons`
3. In terminal, run `apm install file-icons`
4. Start Atom

**Comment by MandarSant** [comment]
@Alhadis thanks it worked

**Comment by Alhadis** [comment]
Lovely. :-)
