### ISSUE TITLE
Updating to “file-icons@2.0.9” failed

### ISSUE THREAD

**Issue by Foadsf** [file-icons/atom#516]
I updated my Atom a couple of days ago and since then I'm having several bugs. today I was promoted to update some plugins but apparently the editor is not able to fetch some data from this pluging repository or something like than. this is the Error I see:

`
Updating to “file-icons@2.0.9” failed
Unable to download https://www.atom.io/api/packages/file-icons/versions/2.0.9/tarball: socket hang up
`

and a screenshot:
<img width="798" alt="screen shot 2017-01-13 at 17 53 54" src="https://cloud.githubusercontent.com/assets/12762442/21938381/6b11d5a8-d9bb-11e6-9c69-d837c0b8edf5.png">

**Comment by Alhadis** [comment]
@Foadsf This isn't something we have any control over. It's an issue with Atom's servers.

I get this too from time-to-time, and it's just a simple matter of restarting Atom and trying again.
