### ISSUE TITLE
Showing manpage icon for files with "archive" in name.

### ISSUE THREAD

**Issue by eyeonpower** [file-icons/atom#517]
Files that have the wording archive in them show up with the manpage icon \E936.

**Comment by Alhadis** [comment]
Screenshot, please.

**Comment by eyeonpower** [comment]
![screenclip](https://cloud.githubusercontent.com/assets/39572/21945274/64dbbf2c-d9a8-11e6-823a-793f57be934a.png)

**Comment by Alhadis** [comment]
That's the terminal icon, not the manpage icon

Fixed.
