### ISSUE TITLE
JavaScript file given npm icon

### ISSUE THREAD

**Issue by 50Wliu** [file-icons/atom#520]
![image](https://cloud.githubusercontent.com/assets/2766036/22008646/073692ca-dc4b-11e6-8a2c-5d8339d69adc.png)
Halp

Dunno what info you need, so here you go.  [update-manager.js](https://raw.githubusercontent.com/atom/about/6848cf97fd30cc1fd097773b3bea2427ae59f080/lib/update-manager.js)
```
Atom    : 1.15.0-dev-d5785a1
Electron: 1.4.13
Chrome  : 53.0.2785.143
Node    : 6.5.0
```
file-icons@2.0.9, no non-default settings.

**Comment by Alhadis** [comment]
Hrm, looks fine to me. Does this persist after the cache is reset?

**Comment by Alhadis** [comment]
You could try assigning a grammar manually (`language-javascript` is stored internally differently to `auto-detect`, I believe), which should trigger an icon update...

**Comment by 50Wliu** [comment]
It's fixed after I assigned the language to something else, forcing an icon change, then reverting to JS.  Setting it to JS first did not help.
Will keep this open for a bit in case it happens again with the same file.

**Comment by Alhadis** [comment]
Need to add more diagnostic features. The information is already available, but asking users to open their dev-console and poke around manually-included class-files is about as user-friendly as `%s`.

~~~c
sprintf($_, some_clever_analogy_that_comes_to_mind_later_on, well_after_I_needed_it);
~~~

**Comment by Alhadis** [comment]
@50Wliu Has this oddity reared its weird-looking head again?

**Comment by Alhadis** [comment]
Gonna take that as a "nope". :D
