### ISSUE TITLE
Git repo hosted on Visual studio is not given valid 'git repo' icon

### ISSUE THREAD

**Issue by cbcoutinho** [file-icons/atom#522]
As title states, a git repo cloned from a visual studio repo is not correctly associated with a repo icon.

I think this has to do with the url of the remote:
Github:
- https example: https://github.com/user/project.git
- ssh example: git@github.com:user/project.git

Visual Studio
- https example: https://example.visualstudio.com/project_group/_git/project
- ssh example: ssh://example@example.visualstudio.com:22/project_group/_git/project

I'm guessing file-icons is grepping the project url, of which Visual studio does not append a '.git' suffix, and results in just a boring folder icon.

Maybe you could also use the '_git' part of the url?

**Comment by Alhadis** [comment]
Ah, not so fast... there was quite recently a bug with showing repository icons, [which is now fixed](https://github.com/file-icons/atom/blob/master/CHANGELOG.md#fixed) and staged for the next release. It might be related.

**Comment by cbcoutinho** [comment]
Oops, sorry man... This is indeed on Windows. And github repos don't work either - I totally misinterpreted the problem.

Just fired up a Linux VM, File-icons has no issue with Github- and/or VS-hosted repos.

*Facepalm*

**Comment by Alhadis** [comment]
All good, mate.

Once I've finished repairing the spec-runner, we can roll out package updates with confidence (it's not running on Windows, kek).

**Comment by dtgoitia** [comment]
Hi there!

Hi!

I am having this issue in Windows 10 too. Any chance to take a look to it when you have a spare minute please?

:)

**Comment by Alhadis** [comment]
Hey @dtgoitia,

Could you attach a screenshot of the affected project window, and tell us what other packages you have installed?

**Comment by dtgoitia** [comment]
Hi @Alhadis,

I am doubting now if my issue does match the thread :S, let me know if you want me to open a new issue please.

My packages are:
```
├── atom-beautify@0.29.26
├── atom-focus-mode@0.11.0
├── atom-html-preview@0.1.22
├── atom-shortcuts@0.0.2
├── file-icons@2.1.7
├── highlight-selected@0.13.1
├── keybinding-cheatsheet@0.1.1
├── language-autolisp@1.0.0
├── language-autolisp-dtgoitia@2.0.0
├── language-latex@1.0.0
├── language-markdown@0.23.0
├── latex@0.43.0
├── markdown-pdf@1.5.0
├── markdown-preview-enhanced@0.12.8
├── markdown-preview-plus@2.4.9
├── markdown-themeable-pdf@1.2.0
├── markdown-toc@0.4.2
├── markdown-writer@2.6.5
├── minimap@4.28.2
├── minimap-find-and-replace@4.5.2
├── minimap-highlight-selected@4.6.1
├── vim-mode-plus@0.93.0
└── Zen@0.18.0
```

Some extra info:
```
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.10.1.windows.1
```

Here the screenshot:
![image](https://user-images.githubusercontent.com/21012855/26894812-6ab91ecc-4bb7-11e7-9ebc-7ba45a8a97fe.png)
The last 5 projects should have the git repository icon as the one's on the top.

Many thanks! :)

**Comment by Alhadis** [comment]
File a new issue, please. Certainly not related.
