### ISSUE TITLE
Atom sometimes crashes on startup

### ISSUE THREAD

**Issue by xob** [file-icons/atom#529]
With the most recent update, 2.0.12, most of the time, when I start Atom, it crashes.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4996802/22339046/ca10ee22-e3b6-11e6-9174-85a4034175c7.png)

When starting with `atom --profile-startup`, everything works fine, every time.

I was not able to locate a crash log file for Atom (not sure if it has one...), but I was able to determine that the problem was File Icons, because when I disabled File Icons (when starting using --profile-startup), Atom stopped crashing when I open it.

I am using Atom 1.13.1 ia32 on Windows 10 64-bit.

Sorry I can't provide log files. If you know how to get them, let me know and I will happily share them.

**Comment by jeyj0** [comment]
Same here, though it seems to create a second session or similar, since Atom stays open after. Only happens sometimes. File Icons seems to be the problem.

Atom 1.11.2 on Ubuntu 16.04LTS 64-bit

**Comment by Alhadis** [comment]
@jeyj0, @xob Try disabling the strategies which use I/O calls to match icons. Add this to your user config:

~~~diff
 "file-icons":
 	coloured: false
+	strategies:
+		hashbangs: false
+		linguist: false
+		modelines: false
~~~

Does that make any difference?

**Comment by xob** [comment]
@Alhadis It still crashes, even when disabling the strategies. Updating to 2.0.13 also didn't fix the issue (just to rule that part out).

**Comment by Alhadis** [comment]
Did you try wiping the `compile-cache` and `blob-store` directories from the `.atom` directory?

When weird shit like this happens, that's usually the first thing I nuke (along with the `recovery` and `storage` folders, just to be sure the slate is as clean as possible).

**Comment by xob** [comment]
I just tried it (deleted both folders), and I still experience the occasional crash on startup. It seems to be crashing about 25-50% of the time.

**Comment by Alhadis** [comment]
Okay, and what other packages and themes do you have installed?

**Comment by xob** [comment]
Here are my currently installed packages:
```
atom-move-line 0.3.3
file-icons 2.0.13
highlight-selecter 0.12.0
increment-me 0.4.1
language-docker 1.1.7
linter 1.11.21
linter-coffeelint 1.2.1
linter-eslint 8.0.0
linter-php 1.3.1
linter-rubocop 0.5.3
minimap 4.26.7
minimap-cursorline 0.2.0
minimap-pigments 0.2.2
pigments 0.39.0
platformio-ide-terminal 2.2.2
pretty-json 1.6.1
project-manager 3.3.3
selection-counter 1.0.0
set-syntax 0.3.2
sort-lines 0.14.0
sync-settings 0.8.1
tablr 1.8.1
```

I don't have any special themes installed. I am using the core theme One Dark for both UI and Syntax.

I could try a fresh Atom install, with just the file-icons package, but that'll have to wait until the weekend.

**Comment by Alhadis** [comment]
At this point, a fresh install sounds like it'll shed the most insight. So if you could, that'd be great, thanks.

**Comment by xob** [comment]
Alright, I'll get back to you once I have tried a fresh install.

**Comment by xob** [comment]
I have tried a fresh install on my laptop (also windows 10), and I was unable to reproduce the problem, unfortunately. I uninstalled Atom, and deleted the .atom folder.

Sadly, I forgot to check if I also had the problem on my laptop before doing the fresh install... so I don't know if it really did fix it, or if I didn't have the problem there at all in the first place.

I'll try a fresh install on my work computer tomorrow morning, and will get back to you.

**Comment by Alhadis** [comment]
Alright, please let me know.

**Comment by xob** [comment]
Ok, on my work computer, with a clean install, with only File-Icons package, I get the crashes.

Here is a step-by-step guid of what I did:
Uninstalled Atom (from Windows' Apps and Features)
Deleted .atom folder
Downloaded Atom installer from Atom website, and installed it
Closed all open windows
Open my project folder
Open 4 files from my project (3 js files, 1 rb file)
Close and re-open Atom
Repeat until I get a crash

I know that my project is a big variable here, but I figured that if I wanted file-icons to crash, I had to have some file-icons displayed.

**Comment by Alhadis** [comment]
A [comment](https://github.com/atom/atom/issues/10397#issuecomment-171517366) in atom/atom#10397 states that Windows crash logs can be found in `[user]\Local\Temp\Atom Crashes`... is there anything insightful there?

If so, please e-mail me the logs or post them on [PasteBin](http://pastebin.com/) for posterity, but please don't paste them directly into this thread.

**Comment by Alhadis** [comment]
Alright, I got your e-mail. :) Digging through the dump-file now, although I'm sure this wasn't supposed to be examined in hexadecimal, haha.

Does Windows' Event Viewer toss up anything useful? The virtualised Win10 install I'm running has **Event Viewer** listed under **Windows Administrative Tools** (from the Start menu), and I'm sure that would help. You mightn't have access if you're on a work computer, though...

**Comment by xob** [comment]
I have checked Windows' Event Viewer, but there was nothing in there. No event at all close to the time of the crashes.

**Comment by Alhadis** [comment]
~~**Yay, the exact opposite of what I hoped to hear!**~~ ... crap.

@50Wliu, my ever-tolerant neighbourhood Windows-using Atom member... do you know of any directories where crash-related data would be stored on Windows when Atom fails to load? Other than `user]\Local\Temp\Atom Crashes`.

**Comment by 50Wliu** [comment]
I believe that's the only place where crashes are stored.

**Comment by xob** [comment]
After a lot of testing, @Alhadis and I have determined that we cannot determine the source of the problem.

Here's a summary of what we know:
I can reproduce the issue on two computers, with all versions of file-icons 2.0+, on Atom 1.12.9, Atom 1.13.0+, and even Atom 1.14.0-beta3.
However, none of the crash events that I experience create any sort of useful log for us to analyze. It does produce logs, but the only thing in them that resembles an exception seems to point at a problem with pathwatcher.

Essentially, we're not even sure if the problem is even related to file-icons, or to Atom itself.

Lacking evidence, and even the ability to progress with the investigation, I am now closing the issue.

If anyone came here hoping to find a fix to the problem, all I can say is be patient, and click that "Reload" button instead of "Close Window". For me, it always works within 2-3 tries.
