### ISSUE TITLE
Icon for .profile is missing

### ISSUE THREAD

**Issue by cbcoutinho** [file-icons/atom#532]
I was looking at some of my dotfiles, and it looks like `.profile` is not being given the correct icon. Right now it's just a gear, whereas I would expect it to be included in some of the shell icons (_a la_ bash, zsh, csh, etc)

Did I miss it somewhere in [config.cson](https://github.com/file-icons/atom/blob/master/config.cson)?

**Comment by Alhadis** [comment]
Hey mate,

Good catch; `.profile` was never included as a pattern. Have remedied that, thanks!
