### ISSUE TITLE
Is it possible to use these icons outside of Atom?

### ISSUE THREAD

**Issue by hackjutsu** [file-icons/atom#533]
Is it possible to use these icons outside of Atom? Like importing a css file in a website. 
(Of course, if the license allows.)

**Comment by Alhadis** [comment]
Of course! Go nuts! :)

Source files for the package's main icon-font can be found at [file-icons/source](https://github.com/file-icons/source).

**Comment by hackjutsu** [comment]
Nice! Thank you!
