### ISSUE TITLE
Problem when "Show icons in file tabs" is enabled with many tabs open

### ISSUE THREAD

**Issue by codeman6100** [file-icons/atom#535]
When "Show icons in file tabs" is enabled and the number of tabs begins to overflow, all text related to the filename/folderpath/etc is lost.  This is only the case when the window width is small or the number of tabs is large.
![screenshot from 2017-02-01 13-28-23](https://cloud.githubusercontent.com/assets/7398125/22520585/e257e154-e882-11e6-9229-a8ccd7ae4b9a.png)
![screenshot from 2017-02-01 13-28-27](https://cloud.githubusercontent.com/assets/7398125/22520584/e2576df0-e882-11e6-8301-dd418f57aff7.png)

**Comment by Alhadis** [comment]
This all depends on what [UI theme](http://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/) you're using. How icons are displayed within tab-panes is determined by the design - their size and margins will vary from theme to theme.

I have an idea, though. We could add a package setting to hide icons once a given number of tabs is reached (determined by the user). Would that work?

/cc @DanBrooker for input

**Comment by codeman6100** [comment]
That would be fine with me, for the time being I have just disabled them on tabs.  Since the Material Theme I am using is one of the more popular ones it was interesting that this was a problem.

**Comment by Alhadis** [comment]
Does the Material Theme apply a CSS class to tabs when they start getting squashed?

If so, you could leverage that in your stylesheet to hide icons when space is an issue:

~~~less
.added-class {
	.title.icon[data-path]::before {
		display: none;
	}
}
~~~

**Comment by DanBrooker** [comment]
I don't another setting which coincidently fixes it is the answer, and it probably won't help fix the next theme issue that pops up.
So either we maintain some theme compatibility (could just be a section in the readme with a snippet of css for the user stylesheet) or we request the theme to add it.

**Comment by Alhadis** [comment]
I'd say you're right, actually. Scratch that idea.

@codeman6100 You're better off bringing this up at the [`atom-material-ui`](https://github.com/atom-material/atom-material-ui) repository. Theme-specific adjustments are something of a last resort.
