### ISSUE TITLE
Some ruby icons missing

### ISSUE THREAD

**Issue by DanBrooker** [file-icons/atom#543]
@Alhadis no rush but thought you should know incase it's a wider issue

<img width="155" alt="screen shot 2017-02-13 at 3 49 58 pm" src="https://cloud.githubusercontent.com/assets/714197/22869481/31f1c6fa-f204-11e6-9cd0-03c460e34dc9.png">

**Comment by Alhadis** [comment]
Oh, those files were recently given [their own icons](https://github.com/file-icons/atom/releases/tag/v2.0.14#new-icons) in `v2.0.14`. It's possible that your stylesheet is applying a different font-family to `Gemfile` and `.rspec` files. This is what you should be seeing:

<img src="https://cloud.githubusercontent.com/assets/2346707/22876308/343a507e-f224-11e6-94a1-59c843b31dee.png" width="430" alt="Figure 1" />

**Comment by DanBrooker** [comment]
Ah new icons that would explain it, the icon font mustn't have reloaded. Reinstalling and restarting has fixed it.
