### ISSUE TITLE
.el, .org icons show x box in folder space and tab bar but normal in ctrl+p finder.

### ISSUE THREAD

**Issue by soulawaker** [file-icons/atom#546]
* ATOM 1.13.0 X64
* file-icons installed a few minutes ago
* folder tree screenshot
![folder-tree](https://cloud.githubusercontent.com/assets/5372217/23075169/ce228d48-f57e-11e6-95c6-b45320057954.jpeg)

* tab bar screenshot
![tab-bar](https://cloud.githubusercontent.com/assets/5372217/23075186/d7a31f9a-f57e-11e6-9a40-8e84284646c5.jpeg)

* ctrl + p finder screenshot
![ctrlp](https://cloud.githubusercontent.com/assets/5372217/23075192/dd3d7bd0-f57e-11e6-9fd8-f99abb1f2b7b.jpeg)

**Comment by Alhadis** [comment]
Have you restarted Atom?

**Comment by soulawaker** [comment]
Yes.

**Comment by soulawaker** [comment]
Ah, another file type icon plugin collisions! 
It's my mistake I'v forgotten totally another plugin installed.
After uninstalling another file type icon plugin, the two icons show normally.
I'm sorry bothering you with my mistakes!
