### ISSUE TITLE
.postcssrc.{js,json,yaml} not working

### ISSUE THREAD

**Issue by daltones** [file-icons/atom#549]
I've just updated to v2.0.16. But `.postcssrc.{js,json,yaml}` is not working yet.

I guess I missed something in my attempt (https://github.com/file-icons/atom/pull/544), probably about that `priority` value I just saw elsewhere.

Sorry for missing the proper test. 😿

**Comment by Alhadis** [comment]
My fault, I should've picked up on that when I merged.

Yeah, icon-rules within the same priority are matched alphabetically. So [`Data`](https://github.com/file-icons/atom/blob/0606a52ddb44799bf342c6e9fd41c21dcc320ec5/config.cson#L1014) and [`JavaScript`](https://github.com/file-icons/atom/blob/0606a52ddb44799bf342c6e9fd41c21dcc320ec5/config.cson#L1969) will obviously be tested before [`PostCSS`](https://github.com/file-icons/atom/blob/0606a52ddb44799bf342c6e9fd41c21dcc320ec5/config.cson#L2992).

**Comment by Alhadis** [comment]
This isn't urgent, so it'll have to wait until the next release. In the meantime, you can always use your stylesheet:

~~~less
.icon[data-name$=".postcssrc.js"]:before,
.icon[data-name$=".postcssrc.json"]:before,
.icon[data-name$=".postcssrc.yaml"]:before{
	content: "\e910";
	top: 2px;
	font-size: 14px;
	font-family: file-icons;
}
~~~

Suppose I'd better update the change-log and release notes, too.

**Comment by daltones** [comment]
Sure, no problem. Thanks! 😃
