### ISSUE TITLE
spec.jsx files

### ISSUE THREAD

**Issue by thiagoterleski** [file-icons/atom#555]
Hi, how can I change style from .spec.jsx files, like:
`AuthLogin.spec.jsx`

These files are for test cases

**Comment by Alhadis** [comment]
It's [explained in the readme file](https://github.com/file-icons/atom#assign-icons-by-file-extension).

Use:

~~~css
.icon[data-name$=".spec.jsx"]:before{
	/* Styling goes here */
}
~~~
