### ISSUE TITLE
Icon for .env files & icon for .vscode directory.

### ISSUE THREAD

**Issue by andreolvr** [file-icons/atom#557]
Create an icon for .env files and an icon for .vscode directory. Thanks 😃

**Comment by Alhadis** [comment]
`.vscode`, sure.

`.env` files, what exactly are you expecting to see? Is a gear-icon not enough?

**Comment by andreolvr** [comment]
.env files are not working on VS Code, theres no gear-icon.

**Comment by Alhadis** [comment]
Hang on, are you using Atom, or Visual Studio?

This is the repository for the Atom package. If you're using VS Code, the correct repository is [file-icons/vscode](https://github.com/file-icons/vscode).

**Comment by andreolvr** [comment]
Oh, sorry. On the bottom of the page https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons says: "Request or contribute new icons here, file-icons/atom they are then imported into this package.". Moving to vscode repository, sorry. :+1:

**Comment by DanBrooker** [comment]
@Alhadis  That'll be my fault, the vscode package just imports the config.cson from here

**Comment by Alhadis** [comment]
Don't worry. =) Some day I hope to develop something that'll streamline font/icon-generation in a variety of formats.

Not just for this package, but for anybody.
