### ISSUE TITLE
Second document HTML5 icon show CSS3

### ISSUE THREAD

**Issue by ziemowitpl** [file-icons/atom#560]
Im copy files from other folder:
[folder]images
index.html
kontakt.html
style.css

and kontakt.html icon is CSS3... rename dont work
but Im rename in con.html and all icons is HTML5 (css3 too)...
Im poses Atom 1.15.0 and file-icons 2.017

**Comment by Alhadis** [comment]
I don't understand what you're trying to say.

Please follow [these steps](https://github.com/file-icons/atom#troubleshooting) and try again. If you still have problems, please include screenshots.
