### ISSUE TITLE
The icons are not showing correctly

### ISSUE THREAD

**Issue by Edge00** [file-icons/atom#562]
![qq 20170320090530](https://cloud.githubusercontent.com/assets/23715779/24086571/a545a302-0d4c-11e7-9338-9dc033bf0efb.png)

**Comment by Alhadis** [comment]
What packages and themes do you currently have installed?

Run this in your terminal, and copy+paste the output:

~~~bash
apm ls --installed
~~~

**Comment by Edge00** [comment]
@Alhadis  Here are the result
Community Packages (5) C:\Users\admin\.atom\packages
├── atom@2.0.17
├── atom-beautify@0.29.17
├── autocomplete-paths@1.0.5
├── emmet-atom@2.4.3
└── minimap@4.26.8

**Comment by Alhadis** [comment]
This folder here:
~~~
C:\Users\admin.atom\packages\atom
~~~

Needs to be this instead:
~~~
C:\Users\admin.atom\packages\file-icons
~~~

How did you install the package? Through Atom's "Packages" menu, or by downloading `file-icons` as a ZIP file?

**Comment by Edge00** [comment]
Yes. i think this is strange. too.
But i installed by
`git clone https://github.com/file-icons/atom.git`
`npm install`
but i found the dir name is't "file-icons" but "atom"
I renamed the dir name just now and it works fine now
thank you~

**Comment by Alhadis** [comment]
My pleasure! Happy to help. =)
