### ISSUE TITLE
RSpec icons now the same as ruby icons

### ISSUE THREAD

**Issue by libbyschuknight** [file-icons/atom#571]
I have just updated this package and all the icons under my spec folder in a Ruby project have changed to the red ruby gem icon. Previously they were the green RSpec icon.

Sorry if this is the wrong place to post this or there is a simply fix but I couldn't find anything about it.

Thanks

**Comment by Alhadis** [comment]
I swear I wrote a comment on this thread, but it's disappeared.

@libbyschuknight Can you post a screenshot please? I don't know what "RSpec" you're referring to.

**Comment by libbyschuknight** [comment]
![screen shot 2017-03-27 at 1 26 30 pm](https://cloud.githubusercontent.com/assets/7097235/24336771/078980b6-12f1-11e7-8f7e-4575c39b10a2.png)

This is a spec file, which is now showing the ruby icon. It use to show a green icon for the spec files, which I think did look a bit different. I can't upload an image of what it was like...

But this:
![screen shot 2017-03-27 at 1 31 48 pm](https://cloud.githubusercontent.com/assets/7097235/24336832/c7300eee-12f1-11e7-959f-0285b3781d2a.png)
This is what it was like and green. 

Found this here https://github.com/file-icons/source/blob/master/charmap.md

😄

**Comment by douglascamata** [comment]
This is a recurring issue, I already reported something similar before in #483 and I confirm the same problem happens again with the latest release of this package.

**Comment by Alhadis** [comment]
I added a new icon for Ruby specs in the latest release:

<img src="https://camo.githubusercontent.com/b66d700a7e0f1c9392153089243891f18f87e116/68747470733a2f2f63646e2e7261776769742e636f6d2f66696c652d69636f6e732f736f757263652f6d61737465722f7376672f546573742d527562792e737667" width="100" />

Problem is, I forgot about specs in nested subdirectories. Meaning `test/subdir/a-spec.rb` won't show the new icon, but `test/a-spec.rb` will.

I could fix this, but you all seem so attached to just a plain Ruby icon, so now I don't know what to do.

**Comment by libbyschuknight** [comment]
Hey, I'm not attached to the plain Ruby icon! I for one would prefer to have a different icon and colour for the spec files. It was extremely useful to easily see the difference when having lots of files open. 
Any reason you can't use the RSpec icon?

And by the way I think file-icons is great! I find it very useful! Thanks for all your hard work on it. 😀

**Comment by libbyschuknight** [comment]
Also, I just moved one of my spec files to be in the `spec` folder and yes it shows that new icon! Yay! I would love it if it could be green instead of red, so it is even more obviously different to a ruby file. I guess I am a sucker for keeping things as is once I discovered I really like something! 😂

**Comment by douglascamata** [comment]
I agree with @libbyschuknight. @Alhadis, we are attached to different color between source and spec/test... doesn't need to be the same icon. And the red/green combination was just perfect!

**Comment by Alhadis** [comment]
This will be resolved in the next release. If you still prefer the test-icon be green, add this to your stylesheet:

~~~less
.test-ruby-icon::before{
	color: #90a959;
}
~~~

And if you prefer the plain old Ruby icon, coloured green:

~~~less
.test-ruby-icon::before{
	font-family: "Octicons Regular";
	content: "\f047";
	font-size: 16px;
	color: #90a959;
}
~~~

**Comment by libbyschuknight** [comment]
@Alhadis thank you!
