### ISSUE TITLE
Where is my file-icons（mac atom）

### ISSUE THREAD

**Issue by Kuohao-wu** [file-icons/atom#573]
![image](https://cloud.githubusercontent.com/assets/16506726/24322978/d068c608-11a8-11e7-96c5-687c5fbd6dde.png)

**I can't download the installation package from APM, so I went straight to the clone project on GitHub, using the NPM installation, and that's what happened to me**

**Comment by Alhadis** [comment]
When you cloned this repository, it was probably cloned to a folder named `atom`. Change it to `file-icons` instead: `packages/file-icons`.

**Comment by Kuohao-wu** [comment]
it work! thanks~
