### ISSUE TITLE
Sass, not using the official logos?

### ISSUE THREAD

**Issue by luni3359** [file-icons/atom#574]
[Here](http://sass-lang.com/styleguide/brand/) it says the seal version of the Sass logo has to be used for square images.

**Comment by Alhadis** [comment]
We *are* using the official Sass logos. A different variant just happens to be used.

I don't like changing defaults, especially ones that've been in use for a long time.

If you prefer the seal version, by all means change it with your stylesheet.

**Comment by luni3359** [comment]
Okay, thank you!
