### ISSUE TITLE
Support for .mjml files

### ISSUE THREAD

**Issue by guidouil** [file-icons/atom#577]
Can you add support for the .mjml files please ?
Here is a quick cutted icon from logo
http://imgur.com/k4fRdzw

And here is there website for reference https://mjml.io

Thanks :)

**Comment by Alhadis** [comment]
Easy, sure thing. =)

BTW, new icon requests should be [submitted here](https://github.com/file-icons/source). ;-)

I'll add an SVG for the icon, but the font will only be updated at the next release.

**Comment by guidouil** [comment]
Sorry for the bad submission, and thank you for your quick reaction 😃
