### ISSUE TITLE
Please slow down the release pace.

### ISSUE THREAD

**Issue by hz** [file-icons/atom#578]
Thanks for the great package with your great effort made for the community. But please slow down the release pace.

**Comment by Alhadis** [comment]
What the heck are you talking about?

**Comment by Alhadis** [comment]
@hz I already try to pace package releases as much as possible. I suggest you be more tolerant, because most of the recent releases have been to fix bugs that other users are experiencing. I'm not going to delay such fixes because some person thinks our release cycle is "too fast".
