### ISSUE TITLE
Nuclide Error

### ISSUE THREAD

**Issue by noah-wisch** [file-icons/atom#582]
I love these icons, but they don't seem to load when using the Nuclide package. Is there a fix for this?

**Comment by Alhadis** [comment]
Are the icons showing okay in the file-tree?

**Comment by Alhadis** [comment]
Ah wait, you're probably referring to all the other icons I'm unable to fix from my end.

I suggest you add your voice to facebook/nuclide#951 and remind them this is still an issue. I've asked them about 5-6 times but they don't seem to give a crap.

**Comment by noah-wisch** [comment]
Will do, thanks!
