### ISSUE TITLE
Icon not showing for Jest files

### ISSUE THREAD

**Issue by jeromelachaud** [file-icons/atom#585]
I have cleared the cache / restart several time

- macOS 10.12.4
- Atom 1.16.0

<img src="https://www.dropbox.com/s/lnjgyhpp5phxsci/Screenshot%202017-04-14%2013.20.32.png?dl=1" />

**Comment by Alhadis** [comment]
@jeromelachaud Were there icons showing before?

**Comment by jeromelachaud** [comment]
Not on this computer actually but they are on another one with the same config.
Hence, me posting this issue.

**Comment by Alhadis** [comment]
And your configuration is...?

**Comment by jeromelachaud** [comment]
The same on both
- macOS 10.12.4
- Atom 1.16.0

**Comment by Alhadis** [comment]
Okay, that still doesn't tell us anything. You're not giving any indication as to what packages you have installed, what the contents of your `config.cson` file are, and what you've added to your user stylesheet. These are the sorts of details that help clarify the cause of the issue.

**Comment by jeromelachaud** [comment]
Cool, there you go 
https://gist.github.com/jeromelachaud/4c908036229ddca1c7eb
[config.cson.zip](https://github.com/file-icons/atom/files/923412/config.cson.zip)

**Comment by Alhadis** [comment]
@jeromelachaud This is an obvious configuration issue, and has nothing to do with the package.

[Your stylesheet](https://gist.github.com/jeromelachaud/4c908036229ddca1c7eb#file-styles-less) contains no icon-related styles whatsoever.

**Comment by jeromelachaud** [comment]
all right, so for the record, I added this to the stylesheet on this computer and it works just fine ✅
```
.icon[data-name$=".test.js"]:before {
  font-family: file-icons;
  content: "\ea64";
 }
```
 though, I still don't understand why I hadn't to do that for my other computer 🤔
