### ISSUE TITLE
`addIconToElement` disposable should revert DOM modifications

### ISSUE THREAD

**Issue by jgebhardt** [file-icons/atom#586]
I'm looking at potentially bringing `file-icons` support back to Nuclide (https://github.com/facebook/nuclide/issues/951 – sorry for the long delay).

Since Nuclide uses React, DOM nodes for file names get re-used _very_ frequently, eg. in quick-open and in the file-tree. I've built a React wrapper that applies `addIconToElement` to the underlying DOM nodes whenever the path changes. However, the disposable returned from `addIconToElement` does not reset the classnames applied by `addIconToElement` to the DOM node. I think it would be cleaner if the disposable not only removed references to the attached node from `file-icons`, but actually reverted all DOM side-effects caused by `addIconToElement`.

```javascript
console.log(element.className);
// 'initial-classname'

const disposable = addIconToElement(element, 'foo.js');
console.log(element.className);
// 'initial-classname js-icon medium-yellow'

disposable.dispose();
console.log(element.className);
// CURRENT: 'initial-classname js-icon medium-yellow'
// IDEAL: 'initial-classname'
```

**Comment by jgebhardt** [comment]
Awesome. Thanks for the quick turnaround!

**Comment by Alhadis** [comment]
Nope, thank YOU for taking care of this for us. Seriously.

Can you ping me once Nuclide has integrated file-icon support, please?

**Comment by jgebhardt** [comment]
@Alhadis just a heads-up, next weeks' Nuclide release will include the [file-icons compatibility fixes](https://github.com/facebook/nuclide/commit/147924b4d4c7d33cd152e5bd0d7166859e1908d8) (and it looks _really_ nice; thanks for all your work on this!)

We usually release Tuesday afternoon-ish (PST), ±24h.

**Comment by Alhadis** [comment]
Oh man, music to my ears. Thank you SO much!

I'll cut a new release right at the same time to minimise friction.

**Comment by jgebhardt** [comment]
It's out! https://github.com/facebook/nuclide/releases/tag/v0.219.0

**Comment by Alhadis** [comment]
Awesome! So is v2.1.4. Thanks for that! 🙏
