### ISSUE TITLE
Remove Nuclide monkey-patching

### ISSUE THREAD

**Issue by jgebhardt** [file-icons/atom#587]
It appears that `file-icons`reaches into (and modifies!) Nuclide code:
https://github.com/file-icons/atom/blob/master/lib/consumers/nuclide.js#L38

This is brittle and breaks as soon as the target submodule goes away, making it harder to evolve our own code base while file-icons is installed:
```
FILE-ICONS: Error patching /Users/jxg/.atom/packages/nuclide Error: ENOENT: no such file or directory, lstat '/Users/jxg/.atom/packages/nuclide/pkg/commons-atom/file-type-class.js'
```

Are you open to removing the special-casing for Nuclide? I understand that you're trying to make file-icons work with all packages out there (which is awesome!), but ideally this would be achieved cleanly through the Atom service API.

**Comment by Alhadis** [comment]
Hi @jgebhardt,

I'm relieved this is finally being considered. Of course we'd be open to removing it. In fact, the long-term goal is to delete everything in `lib/consumers` once Atom's core packages have integrated our service too.

I've applied a fix for #586, but I can't delete the monkey-patch for Nuclide until it's integrated the icon-service in a stable release (at which point I'll happily shoot the hackery).
