### ISSUE TITLE
Tree View file icons not appearing in Atom Beta

### ISSUE THREAD

**Issue by ericbiewener** [file-icons/atom#588]
The icons are fine in my normal Atom, but the beta version doesn't have them. The icons *do* appear on the tabs in the Beta version though.

**Comment by Alhadis** [comment]
@ericbiewener I downloaded and installed 1.17.0-beta2, and the icons are showing up perfectly fine.

What beta version are you currently running? Can you attach a screenshot?

**Comment by ericbiewener** [comment]
It's working now. Maybe they just released a new beta, or restarting it a couple more times did the trick :)
