### ISSUE TITLE
Circle CI 2.0 Support

### ISSUE THREAD

**Issue by Tybot204** [file-icons/atom#589]
Circle CI 2.0 has changed the location of configuration files to `.circleci/config.yml`. It's only in beta currently, but will eventually be replacing Circle CI 1.0 (and the current config located at `circle.yml`).

**Comment by Alhadis** [comment]
Would you prefer the icon be applied to `.circleci/config.yml`, or the `.circleci` folder itself?

**Comment by Tybot204** [comment]
I don't actually know what else goes inside of `.circleci` besides the one config file. It might just be a placeholder for now for features they're adding in the future. The folder itself works though! Thanks for the quick update.
