### ISSUE TITLE
except `default icon` option, are there any other options with the default icon class

### ISSUE THREAD

**Issue by bru4** [file-icons/atom#595]
except `default icon` option, are there any other options with the default icon class.

**Comment by bru4** [comment]
![image](https://cloud.githubusercontent.com/assets/22788621/25778299/7c23c322-332c-11e7-9a6c-253caa05dbd3.png)

**Comment by Alhadis** [comment]
What exactly do you need?

**Comment by Alhadis** [comment]
@bru4 No, there are no other options for default icons, because none are needed.

If there's something you're unable to do with your stylesheet and regular CSS, please file an issue requesting an enhancement. Thank you.
