### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by Lin4aLt** [file-icons/atom#597]
use atom updates 2.0.15 can't update to 2.1.4
uninstall then apm install  still 2.0.15

**Comment by Alhadis** [comment]
Not enough information.

Run this and copy+paste its output:

~~~bash
atom --version; apm --version; apm list -i
~~~

**Comment by Lin4aLt** [comment]
![tim 20170509160456](https://cloud.githubusercontent.com/assets/10914989/25841101/65b960fa-34d1-11e7-8e45-4b81c0cbb9ba.png)

**Comment by Alhadis** [comment]
This isn't a problem with `file-icons`, it looks like your Atom installation is corrupted.

Try reinstalling. If you're still having issues, I suggest you [report this to them](https://github.com/atom/atom/issues).
