### ISSUE TITLE
Disable in tree-view

### ISSUE THREAD

**Issue by sandstrom** [file-icons/atom#600]
Would be great if the icons could be disabled in the tree-view, essentially only shown in the fuzzy-finder (cmd + t).

**Comment by Alhadis** [comment]
Just use your stylesheet:

~~~less
.tree-view .file > .icon::before{
	content: none;
}
~~~

You're welcome. =)

**Comment by sandstrom** [comment]
I am 😄 

But I still think an option would be useful! Sometimes the underlying code changes, and stylesheets need to be updated. It's also more convenient with an option.

**Comment by Alhadis** [comment]
How many settings do you think this package would end up with if we followed that line of thought...? Imagine having options for changing colours, sizes, margins, alignment, and so on...

Now imagine how the confusion befalling a new Atom user who's suddenly unsure how to go about customising his workspace's icons. Stylesheet? Settings? If a desired setting isn't provided, should they request one?

This is why we have CSS: pure freedom to hack the shit out of Atom until we're 100% satisfied with what we see.

Not many users have ever requested a setting to disable icons in the tree-view; the tab-pane is a different story, however.
