### ISSUE TITLE
Horizontal spacing

### ISSUE THREAD

**Issue by zslabs** [file-icons/atom#601]
Hi all!
Using Atom 1.17.0 x64 (Mac), the spacing between the filenames and icons do not match the sidebar; they feel pretty crunched together. Here's an example of the sidebar:

<img width="92" alt="screen shot 2017-05-17 at 10 34 22 am" src="https://cloud.githubusercontent.com/assets/1018402/26159426/90b16016-3aec-11e7-9322-bd808422b7a4.png">

And the top bar:

<img width="493" alt="screen shot 2017-05-17 at 10 34 28 am" src="https://cloud.githubusercontent.com/assets/1018402/26159436/96ff3e84-3aec-11e7-9e6d-388456bf951e.png">

I believe they had a bit more space between them in previous versions, so maybe something with the Atom update messed with this a bit. Thanks!

**Comment by Alhadis** [comment]
Hey there,

That's strange. I'm running the same version and OS as you, but haven't noticed a difference in advance widths. Could you please tell me what theme you're using?

**Comment by zslabs** [comment]
Hi,
I'm using the One Dark theme (UI and syntax).

**Comment by pezza3434** [comment]
Same issue here

**Comment by zslabs** [comment]
Digging into this a bit more, it does look like there's a difference in spacing in the CSS.

Here's the sidebar:

<img width="339" alt="screen shot 2017-05-17 at 11 53 19 am" src="https://cloud.githubusercontent.com/assets/1018402/26163379/89b7de06-3af7-11e7-97ba-677b4e1dffb7.png">

And the top bar:

<img width="340" alt="screen shot 2017-05-17 at 11 53 31 am" src="https://cloud.githubusercontent.com/assets/1018402/26163386/904de8f0-3af7-11e7-8f09-78ce7a1ec266.png">

Kind of a weird mix of `px` and `em`, so possibly some core Atom styles changed?

**Comment by pezza3434** [comment]
Also, is it just me or have the panel tabs got a lot narrower?

**Comment by thisisnealpatel** [comment]
Same issue here.

**Comment by Alhadis** [comment]
Looks like [this was deliberate](https://github.com/atom/one-light-ui/pull/100). This part fell right on the money, too:

> __Possible Drawbacks:__  
> This might override icon packages.

They've actually done the right thing; in fact, using `em` units is something this package should've been doing from day 1. Seems we're stuck with pixel measurements now... switching to `em` units would probably have pretty far-reaching consequences.

Anyway, the lack of breathing space is easily solved on our end:

~~~css
.tab-bar .tab .title:before{
	width: 1em;
}
~~~

Result:  
<img src="https://cloud.githubusercontent.com/assets/2346707/26168509/9f10f306-3b7d-11e7-8774-1b0eb022a99a.png" alt="Figure 1: @2x" valign="middle" /> <img src="https://cloud.githubusercontent.com/assets/2346707/26168509/9f10f306-3b7d-11e7-8774-1b0eb022a99a.png" alt="Figure 1: @1x" width="124" valign="middle" />

I'd prefer not to touch the icon-sizes, though. We shouldn't be fighting with theme styling anymore; and I'd prefer we avoid doing so, too. If you guys want to enlarge the icons, you can always crank the `font-size` of the icons with your stylesheets:

~~~css
.tab-bar .tab .title:before{
	font-size: 1.5em; /* …etc */
}
~~~

**Comment by Alhadis** [comment]
This is probably worth releasing a hotfix for, since One Dark is such a commonly-used theme (and I hate to imagine how many users have already been bugged by this since Atom v1.17 was released).

**Comment by Alhadis** [comment]
Okay, [published](https://github.com/file-icons/atom/releases/tag/v2.1.6)! Sorry if that took too long...
