### ISSUE TITLE
Error installing file-icons 2.1.6 on Atom 1.17.2

### ISSUE THREAD

**Issue by bitbox** [file-icons/atom#607]
Hi !

Don't know if I'm the only one facing this issue but when trying to install the file-icons 2.1.6 package on Atom 1.17.2, I get the following error:

**Installing “file-icons@2.1.6” failed.
npm ERR! cb() never called!`**

Had the same result in 1.13.x, then updated Atom to 1.17.2 thinking this might fix the problem but had no luck :-(

Any advise would be welcome.

Thanks

**Comment by Alhadis** [comment]
Could you copy+paste the output of `apm --version`, please?

**Comment by bitbox** [comment]
Here you go:

> apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.9
git 2.1.4

**Comment by Alhadis** [comment]
Not having much luck pinpointing a culprit, here.

Could you try installing with verbose output, please? There'll be a lot of feedback: you should paste it into a Gist or upload it to [PasteBin.com](https://pastebin.com/).

~~~bash
apm install --verbose file-icons
~~~

**Comment by bitbox** [comment]
You can find the 1500 pasted lines here:
https://pastebin.com/4GuRtWxd

Thanks for looking into this !

**Comment by Alhadis** [comment]
Ugh, this isn't telling me anything either.

Does this work?

~~~sh
apm install --production file-icons
~~~

Installing a package through command-line will also install `devDependencies`; and since that includes Mocha, it's attempting to download a shitload of NPM modules it requires. As a guess, it seems to be timing out somewhere along the way.

I can't reproduce the timeout on my end, though... probably because it's being pulled off a different server:

**My local server:** `cache-mel6523-MEL` (Melbourne)
**Your local server:** `cache-ams4124-AMS` (Amsterdam; hej maat, ben jij een nederlander? :P)

Anyway, if this is a CDN-related issue, there's nothing either of us can really do because it's not our fault, heh.

**Comment by bitbox** [comment]
output of with --production option:
> apm install --production file-icon
Installing file-icon to /home/thibaut/.atom/packages ✗
Request for package information failed: Not Found

I must say I have no clue either, using the --production option returned (quasi)instantaneous output, so timeout doesn't seem to be a possible cause in this case. It states "Request for package information failed: Not Found" but, as I have no knowledge regarding the Atom installation process I must say I'm impotent.

And, no, I'm not Nederlander, I'm Belgian :-)

**Comment by Alhadis** [comment]
Ah, you spelt the package's name wrong. You forgot to pluralise it. =)

~~~diff
-apm install --production file-icon
+apm install --production file-icons
~~~

(I'm gonna take a wild guess and say you're from the French-speaking part? ;)

**Comment by Alhadis** [comment]
@bitbox If the `--production` switch doesn't help, you could also try wiping the `~/.atom/.apm` in case there's a corrupted download in there somewhere. Forcing APM to repopulate its local cache might help...

Other than that, there's really nothing else I can do to help... 😞  Sorry.

**Comment by bitbox** [comment]
THANK YOU @Alhadis !

Wiping out the content of ~/.atom/.apm/ did the trick :-D
The update went smoothly after 'rm -rf ~/.atom/.apm/* && rm -rf ~/.atom/.apm/.*', I was able to update the file-icons package stright from the atom interface !
Thanks a lot !

Oh! and you guessed right: je parle français, maar ook een beetje nederlands ;-)

**Comment by Alhadis** [comment]
Oh man, glad to hear that! Thanks for being patient. :D

(It was the space before your exclamation marks that gave the French away, haha :D)

If there're any further problems, don't hesitate to open another issue. =)
