### ISSUE TITLE
Folder Icons - next update?

### ISSUE THREAD

**Issue by VeCZernicek** [file-icons/atom#608]
Hello,
I want to thank you for your work, it is really good and I want to ask, if it is possible to import the open folder icons in the next update. 

Something like in [_Insomnia_](https://insomnia.rest).
![folder](https://cloud.githubusercontent.com/assets/9391396/26622021/3084fe5c-45e9-11e7-978f-222b8a985ea6.JPG)

The difference between open and closed folders.
Thank you.

**Comment by Alhadis** [comment]
Hey @VeCZernicek, very sorry for such a relayed response... I thought I already answered this earlier.

Both of the folder icons you've suggested are part of the [Font Awesome](http://fontawesome.io/icons/) set. You can easily use them right now with your stylesheet. Something like the following should work:

~~~less
.directory.entry > .header > .icon-file-directory::before{
	font-family: FontAwesome;
	content: "\f07b";
	
	&.expanded{
		content: "\f07c";
	}
}
~~~

I'd rather not use make this the new default, however.
