### ISSUE TITLE
File icons in the file tabs are not colored

### ISSUE THREAD

**Issue by jcarrete5** [file-icons/atom#612]
## File icons in the file tabs are not colored
I noticed that when using the `Atom Material UI` theme _specifically_, the file icons for the file tabs at the top of the window remain uncolored whereas the file icons for the file tree on the left are colored. The file icons package worked perfectly for other themes such as `One Dark` and `Atom Dark`

This occurs immediately whenever a file is opened in the editor. I have not changed any of the file icons from their default state.

#### Uncolored file tabs
![file-tabs-not-colored](https://user-images.githubusercontent.com/6133706/26847403-f44ae6ae-4aca-11e7-8665-68a14eb28917.png)
#### Colored file tree
![image](https://user-images.githubusercontent.com/6133706/26847610-b0183ee0-4acb-11e7-9fea-01be9e88a919.png)

**Comment by Alhadis** [comment]
@jcarrete5 It sounds like you might be better off filing a report to the [`Atom Material theme`](https://atom.io/themes/atom-material-ui) directly, instead of here.

**Comment by jcarrete5** [comment]
Hmm, I think you are right. There is an open issue on their repository.
