### ISSUE TITLE
C header files

### ISSUE THREAD

**Issue by steronydh** [file-icons/atom#614]
Could .h files have an 'H' icon instead of a 'C'?

**Comment by Alhadis** [comment]
Nope, sorry. I recommend [using your stylesheet](https://github.com/file-icons/atom#icon-reference) instead.

~~~less
.c-icon[data-name$=".h"]:before{
	font: 800 16px Helvetica, sans-serif;
	content: "H";
}
~~~

You'll need to play with font-styles and sizes better yu create an `H` icon that you're satisfied with.

**Comment by steronydh** [comment]
Perfect, thanks.
