### ISSUE TITLE
Uncaught TypeError: styleSheet.cssRules[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by Gorgulho** [file-icons/atom#618]
I have update the package yesterday, and always I open the atom this error apears:

![captura de ecra de 2017-06-20 14-31-03](https://user-images.githubusercontent.com/24915150/27335661-3c2d2cca-55c5-11e7-8094-2efad3f74046.png)

what can I do?

**Comment by Alhadis** [comment]
What version of Atom are you running, and what operating system are you using?

**Comment by Alhadis** [comment]
Also, are you SURE you're using the latest version of `file-icons`? It should be `2.1.7`.

**Comment by Gorgulho** [comment]
**atom version:**0.181.0
![captura de ecra de 2017-06-20 14-35-28](https://user-images.githubusercontent.com/24915150/27335833-b9cfebe0-55c5-11e7-9a60-4488bdd60857.png)

**Comment by Alhadis** [comment]
Do you mean `Atom v1.18` ...? An Atom version of `0.181.0` is impossible.

You also haven't told us your operating system...

**Comment by Gorgulho** [comment]
the atom version I have seen wrong, is the version 1.11.2, I will update right now

**Comment by Gorgulho** [comment]
And my operating system is Fedora 22

**Comment by Alhadis** [comment]
Do you have automatic updates turned off? You should really be keeping them **enabled**, because your Atom version hasn't been updated in 8 months...

Another user reported the [same issue](https://github.com/file-icons/atom/issues/572) in March, and they were running an even older version of Atom. I'm wondering if I shouldn't just crank the minimum required Atom version to something more recent...

**Comment by Gorgulho** [comment]
This atom is from pc from my office, I don't know if the updates are turn on or off, but I don't find nothing like that on atom. do you know where is that option?

**Comment by Alhadis** [comment]
In the main settings panel, you should see a preference called **Automatically update**:

<img width="367" alt="Figure 1" src="https://user-images.githubusercontent.com/2346707/27336889-3fa8054c-5614-11e7-815c-f3499b9c7243.png" />

**Comment by Gorgulho** [comment]
That option are already selected, but the atom never show the updates

![captura de ecra de 2017-06-20 14-59-29](https://user-images.githubusercontent.com/24915150/27336986-14f47f7e-55c9-11e7-9870-1562daa8662b.png)

**Comment by Alhadis** [comment]
Are you still seeing this error after installing Atom v1.18?

**Comment by Gorgulho** [comment]
I can't update the atom, I don't know why

**Comment by Alhadis** [comment]
Try doing a fresh install using the latest version from [`atom.io`](https://atom.io/). If you're trying to update from inside Atom, it's probably going to fail for the same reasons why its automatic updates are failing.

**Comment by Alhadis** [comment]
Finally got to the bottom of this. Gonna post my research here for posterity's sake...

After installing Atom v1.11.2 on a virtual machine, I inspected `document.styleSheets[0].cssRules` in the devtools, and noticed `Symbol.iterator` was missing from its prototype.

Now, that particular version of Atom ran Chrome 49, and iterator support in DOM interfaces [didn't land until Chrome 51](https://www.chromestatus.com/features/5750902036103168). Meaning that array-like DOM objects (e.g., [`NodeList`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList), [`CSSRuleList`](https://developer.mozilla.org/en-US/docs/Web/API/CSSRuleList), etc) couldn't be iterated over like an ordinary array. I'd forgotten this when I was writing the CSSOM manipulation code.

~~~js
for(let i of document.styleSheets[0].cssRules); // <= Chrome 50: Breaks
for(let i of document.styleSheets[0].cssRules); // >= Chrome 51: Works
~~~
