### ISSUE TITLE
TypeScript test icon pattern

### ISSUE THREAD

**Issue by mmermerkaya** [file-icons/atom#621]
In TypeScript, it's common to have the test code next to the source code that is being tested. Some examples are:
[TypeScript React Starter](https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter): `src/App.tsx` and `src/App.test.tsx`.
[Angular QuickStart](https://angular.io/guide/quickstart): `src/app/app.component.ts` and `src/app/app.component.spec.ts`.
Both of these are official docs.

According to the [regex here](https://github.com/file-icons/atom/blob/master/config.cson#L4002), (if I understood correctly) these test files don't get the test icon, because they are not under a directory named test/ (or a variation of it).

Is it possible to change this behavior, so all file names that end in `(spec|test).tsx?` get the test icon?

**Comment by Alhadis** [comment]
Yep, done! Thanks!

**Comment by mmermerkaya** [comment]
That's great, thank you! :)
