### ISSUE TITLE
Colors No Longer Showing Up In Tree View

### ISSUE THREAD

**Issue by DamSenViet** [file-icons/atom#624]
Color settings are turned ON but atom won't show the proper file-type colors. My aesthetic self is now sad.

**Comment by Alhadis** [comment]
Your aesthetic self can help by listing what themes and packages you currently have installed and active.

**Comment by DamSenViet** [comment]
Currently using Atom Material with One Dark syntax. I've tried out other icon packages with colors (e.g. seti-icons) and those seem to work just fine. I also tried One Dark UI with One Dark syntax; no dice.

list of other downloaded packages:

- minimap
- platformio ide terminal
- pigments
- emmet
- file-icons (obv)

**Comment by Alhadis** [comment]
Would you happen to have the package's `Only colour when changed` setting enabled, perchance?

If so, the only files that will display any colour are those in a Git repository which have uncommitted modifications.

A screenshot would also help, BTW.

**Comment by DamSenViet** [comment]
That fixed the issue. I was just being really stupid. My bad.

**Comment by Alhadis** [comment]
Understandable, have a great day.

**Comment by surdu** [comment]
I've also been fooled by this. Maybe that option should be disabled by default ?

**Comment by Alhadis** [comment]
@surdu What do you mean? The `Only colour when changed` setting *is* [disabled by default](https://github.com/file-icons/atom/blob/8fedcfdd67d97b771a7ac7c4d55820921a9c9d54/package.json#L50)...

**Comment by surdu** [comment]
I really should quit drinking ...
