### ISSUE TITLE
No icons in tree-view

### ISSUE THREAD

**Issue by Leithian** [file-icons/atom#626]
Hi,
I just stared using file-icons, especially for the .tex-files I often edit in Atom. The icons did not automatically change, but after I added them manually in my stylesheet they showed up in the tabs, but in the tree-view I still get nothing more than colored rectangles.
I'm using Atom 1.19.0-beta3 on Windows 10.
Also, changing the font size changed nothing, not in the tabs nor in the tree-view.
Still, great work!!
![file-icons error](https://user-images.githubusercontent.com/6052614/28014677-e04f50b4-656d-11e7-8203-440deec5d11d.png)

**Comment by Alhadis** [comment]
Did you download this to a folder called `atom`, or a folder called `file-icons`?

If it's the former, rename it so it's `file-icons`. If it's the latter, then we have a problem. I'm guessing it's the former, though...

**Comment by Leithian** [comment]
I downloaded it in Atom which put in into C:\Users\**\.atom\packages\file-icons

**Comment by Alhadis** [comment]
Oookay, so there's obviously a conflict happening somewhere.

Two things:

1. Open the dev-tools, and inspect the tree-view elements with missing icons. Select the `::before` pseudo-element, and tell me what font-family it's using. You should see `font-family: file-icons;`:
	<img src="https://user-images.githubusercontent.com/2346707/28015717-83c405f0-65b4-11e7-9517-615ab70fc6b7.png" width="319" alt="Figure 1" />  
	If it's crossed out, it means something else (probably another package) has overridden it.

2. Could you give me a list of packages and themes that're installed (and active)? Copying the output of `apm ls -i` will do.

**Comment by Leithian** [comment]
The `::before` element returns `.tex-icon:before`, where nearly everything is crossed out because I've overwritten it to get the tab icons working, but in `.icon[data-name$=".tex"]:before` it does say `font-family: file-icons;`. Is it normal that there is `.tab [data-name]:before, .tree-view:not(.nuclide-file-tree) [data-name]:before` before that where it says `font-family: 'Octicons regular'`?

 `apm ls -i` returns:

> ├── atom-clock@0.1.13
> ├── atom-latex@0.7.11
> ├── atom-material-syntax@1.0.6
> ├── atom-material-ui@2.0.4
> ├── autocomplete-python@1.9.1
> ├── file-icons@2.1.8
> ├── file-type-icons@1.3.4
> ├── glowing-cursor@0.1.2
> ├── highlight-selected@0.13.1
> ├── language-latex@1.0.0
> ├── latex@0.44.0
> ├── latexer@0.3.0
> ├── material-ui@1.0.10
> ├── minimap-bookmarks@0.4.2
> ├── minimap-codeglance@0.4.7
> ├── minimap-cursorline@0.2.0
> ├── minimap-find-and-replace@4.5.2
> ├── minimap-highlight-selected@4.6.1
> ├── minimap-plus@4.29.1
> ├── minimap-selection@4.4.0
> ├── neon-selection@0.3.2
> ├── pdf-view@0.59.0
> └── script@3.15.0
, but `language-latex` and `latex` are not enabled.

**Comment by Leithian** [comment]
Oh, I just realized that I still had the package "file-type-icons" enabled, that solved it. I'm sorry for any inconvenience caused. Thanks for your help and your (now even better) package!

**Comment by Alhadis** [comment]
Haha, was just about to point that out to you. =) No problem, and thank you!
