### ISSUE TITLE
Opened folder icon 

### ISSUE THREAD

**Issue by ikorchenov** [file-icons/atom#630]
Please add icon of opended folder for class "icon-file-directory open-folder" in tree-view.

**Comment by Alhadis** [comment]
Hrm, what UI theme are you using? Is this class already being applied by another package you've installed?

Another user brought up a similar issue in [`#608`](https://github.com/file-icons/atom/issues/608) a couple of months ago, but I suggested he use an existing icon from [Font Awesome](http://fontawesome.io/icons/) instead:

~~~less
.directory.entry > .header > .icon-file-directory::before{
	font-family: FontAwesome;
	content: "\f07b";
	
	&.expanded{
		content: "\f07c";
	}
}
~~~

I mean, I COULD add an icon for an opened folder, but it would have to match the size and style of the folder icons used in Octicons (the font providing the default closed-folder icon). Things might get a bit messy if UI themes have different-looking icons that don't match the package's open-folder icon...

Does this make sense?
