### ISSUE TITLE
How to set icon for custom file type?

### ISSUE THREAD

**Issue by t0msk** [file-icons/atom#631]
Hello,

I use a template file (*.tpl) which contains HTML code. How is possible to set a HTML icon for that file (tpl)?

Thank you

**Comment by Alhadis** [comment]
Add this to your user config's `customFileTypes` setting:

~~~cson
"text.html.basic": [
  "tpl"
]
~~~

You can find more info on [adding custom filetypes here](http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition).

**Comment by t0msk** [comment]
Thank you :)

**Comment by Alhadis** [comment]
You're welcome!

**Comment by t0msk** [comment]
Please one more question, can I ask you? If I want another files its like:

```
    customFileTypes:
      "text.html.basic": [
        "tpl"
      ]
      "source.cpp": [
        "mdl"
      ]
```
? Because at mdl file extension it doesn't show CPP icon.

**Comment by Alhadis** [comment]
Yes, that should be working. What is it showing instead?

**Comment by t0msk** [comment]
Its some kind of blue "onion" http://i.imgur.com/gXRelid.jpg That file is Perl, but if I write source.perl or source.cpp always there is that "onion", and logo of Perl is Camel, so I don't understand.

**Comment by Alhadis** [comment]
Yes, that's the logo of [the Perl Foundation](http://www.perlfoundation.org/). =) I'm guessing the file has a modeline or a hashbang inside it, am I correct? Something that looks like this?

~~~perl
#!/usr/bin/env perl
# -*- perl -*-
# vim: set syntax=perl:
~~~

If it does, that's to be expected. It's the author's way of identifying the file as containing Perl code. If you create a new `.mdl` file and save it elsewhere, you'll find it has the C++ icon like you expect.

**Comment by t0msk** [comment]
Ah yes, I understand :) yes I have `#!/usr/bin/env perl` :) ok so it is logo of Perl Foundation, because I didn't know it, but now I know :) Thank you very much :)

**Comment by Alhadis** [comment]
BTW, it's a play on words. The onion refers to [Pearl onions](https://en.wikipedia.org/wiki/Pearl_onion). =)

**Comment by t0msk** [comment]
Haha interesting :)
