### ISSUE TITLE
GIMP palette support

### ISSUE THREAD

**Issue by gizmecano** [file-icons/atom#632]
I was glad to see additions for GIMP support in the last [version 2.1.10](https://github.com/file-icons/atom/releases/tag/v2.1.10), but what about the `.gpl` file type (used for palette)?

As described in _[Chapter 7. Painting with GIMP](https://docs.gimp.org/2.8/en/gimp-concepts-palettes.html)_:

> GIMP palettes are stored using a special file format, in files with the extension `.gpl`. It is a very simple format, and they are ASCII files, so if you happen to obtain palettes from another source, and would like to use them in GIMP, it probably won't be very hard to convert them: just take a look at any `.gpl` and you will see what to do. 

I suppose that this file type could be easily displayed with the same [GIMP icon](https://github.com/file-icons/source/blob/master/svg/GIMP.svg) than `.xcf`, `.ggr`, `.gih`, `.vbr` without adding a new one.

**Comment by Alhadis** [comment]
Haha, I actually don't use GIMP, myself. :) I'll add it, although you'll need to wait until the next package release to see it.

Are there any other extensions that are missing?

**Comment by gizmecano** [comment]
Right now, I only noticed this one as missing (and mostly because it's one of the config file type I often use in version control)...

No problem for waiting: I use Atom without this icon for a while, I can be patient... 😉

**Comment by Alhadis** [comment]
Alright, done! You could also `cd` into the package directory, run `apm install .` and then edit `config.cson` yourself to apply the changes made in 636dfad.

**Comment by gizmecano** [comment]
Thanks. 👍
