### ISSUE TITLE
Confusing icon for files/folders named "server"

### ISSUE THREAD

**Issue by glaslos** [file-icons/atom#633]
Any file or folder called `server` get a rather confusing, empty page like looking icon.

![image](https://user-images.githubusercontent.com/716339/29078205-fc62df16-7c59-11e7-8721-fbefb582baf9.png)

**Comment by Alhadis** [comment]
It's likely a caching issue with different filetypes. Try running [these steps](https://github.com/file-icons/atom#an-icon-has-stopped-updating) and tell me if the issue persists.

**Comment by Alhadis** [comment]
@glaslos Can you confirm if clearing the workspace's icon-cache fixes your issue?

**Comment by glaslos** [comment]
@Alhadis will test it when I'm back in the office tomorrow and update here.

**Comment by glaslos** [comment]
Hi @Alhadis thanks, this fixed the issue and the icons now look as expected.

**Comment by Alhadis** [comment]
Glad to hear it! :-) Don't hesitate to speak up again if you encounter any further issues, alright?
