### ISSUE TITLE
consider publish the icons + icondb.js to npm

### ISSUE THREAD

**Issue by thisconnect** [file-icons/atom#641]
Would you consider publishing the icon tables + webfonts + css to npm?

I am planing to using file-icons/atom outside of atom

i.e

```javascript
const iconTable = require('file-icons/lib/icons/icon-tables')

console.log(iconTable.matchName('file.json'))
```

**Comment by Alhadis** [comment]
Hey mate,

There's an unofficial port of it, but it's not affiliated with us: check out [`file-icons-js`](https://www.npmjs.com/package/file-icons-js). It also hasn't been updated in several months, and is using code that's subject to change in future.

I *could* publish a standalone NPM module for this, but I'd need to know up-front that there's enough demand to warrant maintaining this package as an external library...

**Comment by Alhadis** [comment]
@thisconnect I've been giving this more serious thought lately, and I do indeed plan on making `file-icons` available to browsers and Node programs (officially).

Going to close this as it's technically a duplicate of #629. Please subscribe there for further discussion and to be notified of how things develop. =)

**Comment by Alhadis** [comment]
Reopening this, because it's ultimately the long-term direction for this package (which I hope to migrate from "package" to "portable icon library with file-matching superpowers).

**Comment by Alhadis** [comment]
https://github.com/file-icons/atom/issues/422#issuecomment-480771381
