### ISSUE TITLE
Handle pytest files, as test-python-icon icons

### ISSUE THREAD

**Issue by blackillzone** [file-icons/atom#642]
Currently, only test files with this format are using the correct icon:
`myprogram_test.py`

Using the [pytest](https://docs.pytest.org/en/latest/) framework, the name format of the test file is:
`test_myprogram.py`

So, I've adapted the regexp used in `.icondb.js` (i'm clearly not good at regexp, so maybe it can be improved):

```
["test-python-icon",["dark-blue","dark-blue"],/([\\\x2F])(test|spec)s?(\1((?!\1).)+)*\1((?!\1).)+[._-](spec|test)s?\.py(3|thon)?|([\\\x2F])(test|spec)s?(\8((?!\8).)+)*\8(spec|test)s?[._-].+\.py(3|thon)?$/i,1.5,true],
```

Do you think it can be something to add natively in this package ?

**Comment by Alhadis** [comment]
👋 Hey @blackillzone,

The contents of `.icondb.js` *really* shouldn't be edited by hand. The correct file to edit is [`config.cson`](https://github.com/file-icons/atom/blob/master/config.cson). What you see in `.icondb.js` is actually a combination of expressions concatenated from multiple similar rules.

And yes, of course. Basically, should the "Python test" icon be applied to any filename which matches `/^test_[-\w]+\.py$/i`...?

**Comment by blackillzone** [comment]
Hi @Alhadis,

Oh I see, sorry for this misunderstanding (I'm also bad at JS ^^').

And yes, I think that all files under a test folder (folder named test or tests, like the actual regexp), with the `test_*.py` format or `*_test.py` should use the "python test" icon.

For example, each cases:
```
tests/
├── test_files.py
└── users_test.py
test/
├── test_files.py
└── users_test.py
```

The format changes depending on the testing framework used (they couldn't do something common, sadly...).

Thanks for the quick answer.
