### ISSUE TITLE
there is no node_modules icon

### ISSUE THREAD

**Issue by TrinityN858** [file-icons/atom#644]
I created a file folder for node_modules in atom - but the icon for the node_modules was not created for the folder. So, what do I need to do? Thanks

**Comment by Alhadis** [comment]
@TrinityN858 Which version of Atom are you running, and what operating system are you using?

Also, could you please copy+paste the output of `apm ls -ib` so we can see what packages you have installed?

**Comment by TrinityN858** [comment]
@Alhadis Atom version 1.19.5, operating system is the mac os

what do you mean by the 'output of apm 1s -ib'? I do not understand

**Comment by Alhadis** [comment]
> what do you mean by the 'output of apm 1s -ib'? I do not understand

Sorry, I should have been clearer. I meant to ask "could you please run the following command in your terminal and copy+paste what it shows you?"

**Comment by Alhadis** [comment]
@TrinityN858 Did this happen straight after installing `file-icons`? If so, you'll need to restart Atom before things are 100% smoothed-over. It's a (hopefully) temporary limitation of the package, I'm afraid.

**Comment by TrinityN858** [comment]
@Alhadis Yes, I restarted the Atom last nite after installing it - but there was no icon for the node_modules. I restarted the Atom a moment ago - NOW, the icon populated!!! Strange, but it works now!!! YAYY, I am super happy to be using this!!! Thank you so much for your quick response!!! ;)

**Comment by Alhadis** [comment]
Great to hear! 😀 

I think I need to add an issue template that lists the usual questions we ask all the time... 🤔
