### ISSUE TITLE
Installing “file-icons@2.1.11” failed.

### ISSUE THREAD

**Issue by Twiistrz** [file-icons/atom#646]
Installing “file-icons@2.1.11” failed.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Twiistrz\.atom\packages\file-icons\styles\fonts.less'
    at Error (native)

**Comment by Alhadis** [comment]
Hey @Twiistrz,

It sounds like the package failed to download. Try installing from the command-line:

~~~bash
apm install --production file-icons
~~~

**Comment by Alhadis** [comment]
Closing this as it isn't package-related. If you're still having troubles installing, try uninstalling and reinstalling the package.
