### ISSUE TITLE
color change in icons

### ISSUE THREAD

**Issue by andykimchris** [file-icons/atom#650]
my colors vanished from my icons.Please help.

**Comment by Alhadis** [comment]
1. Go to **Settings**
2. Click the **Packages** tab in the sidebar
3. Search for `file-icons`
4. Go to the package's settings
5. Make sure the first two checkboxes are set to this:
<img src="https://user-images.githubusercontent.com/2346707/30904383-3b8e3910-a3b5-11e7-8b7d-41f6b7c40827.png" width="527" alt="Figure 1" />

**Comment by andykimchris** [comment]
Thanks.Appreciate it
