### ISSUE TITLE
Add icon for Aptfile (same as Procfile)

### ISSUE THREAD

**Issue by adamreisnz** [file-icons/atom#656]
For the heroku APT buildpack configuration, an `Aptfile` is used:

![image](https://user-images.githubusercontent.com/490562/31421284-0adaa378-aea3-11e7-9620-4d1d53943e16.png)

Could it get the same icon as the `Procfile`?

![image](https://user-images.githubusercontent.com/490562/31421291-132d070a-aea3-11e7-8a20-59da85bac56d.png)

**Comment by Alhadis** [comment]
Done! You just made it under the door; I was planning to cut a release this afternoon. Which should've been done this morning, but I got sidetracked. 😀

**Comment by adamreisnz** [comment]
So fast! Awesome 🎉

**Comment by Alhadis** [comment]
The existing `/Procfile/` pattern was being matched case-sensitively, BTW, so I've assumed the same of `Aptfile` too. :) Let me know if that should be amended.

**Comment by adamreisnz** [comment]
Yes that's fine, I think they require a capital first letter for the filename 👍
