### ISSUE TITLE
Option to unset the colored icons in the tabs

### ISSUE THREAD

**Issue by GrimLink** [file-icons/atom#658]
Recently on Atom-Material-UI there has been commit on the fact that the icons are not colored in the tabs (https://github.com/file-icons/atom/issues/652) (https://github.com/atom-material/atom-material-ui/issues/349).

It great that this has been fixed but for users that use the color from the Atom-Material-UI for the tabs should have the option to set the icon color off.

Plz include the option to unset the coloring for the tabs only.

![screen shot 2017-10-14 at 21 12 41](https://user-images.githubusercontent.com/4387541/31578606-c34029e6-b124-11e7-8978-c2b11f45ebda.png)
![screen shot 2017-10-14 at 21 13 11](https://user-images.githubusercontent.com/4387541/31578607-c35ac21a-b124-11e7-859c-40dd2850e4fc.png)

**Comment by Alhadis** [comment]
There's no need for an option. Just add this to your stylesheet:

~~~less
 // Show uncoloured icons in the tab-bar pane only
 .tab-bar .tab .title.icon::before{
 	color: inherit;
 }
~~~

**Comment by GrimLink** [comment]
Also a good option.
Thx @Alhadis 😉
