### ISSUE TITLE
Add text-shadow / custom style

### ISSUE THREAD

**Issue by Arcadia822** [file-icons/atom#659]
I'm trying to manually add some text-shadow to the icons like this theme: https://atom.io/themes/steam-pirate-ui. But found it difficult to hard code all the color matching the package.

Could you add it as an option or add some sort of custom style functionality ?

**Comment by Alhadis** [comment]
Why? None is needed. What CSS have you tried to use?

**Comment by Alhadis** [comment]
This will be a simple styling issue. I'm happy to help if you show me what CSS you're using.

However, adding an option to do what CSS is designed to do simply isn't going to happen.
