### ISSUE TITLE
Request: bs-config.js

### ISSUE THREAD

**Issue by bennypowers** [file-icons/atom#662]
Please consider adding the browser-sync logo for files named `bs-config.js`

```svg
<!-- from browsersync.io -->
<svg id="svg-logo" viewBox="0 0 140 204.1" width="100%" height="100%">
  <path d="M63.5.3L1.7 31.2c-1 .5-1.7 1.5-1.7 2.7v136.3c0 1.1.6 2.2 1.7 2.7l61.8 30.9c2 1 4.3-.5 4.3-2.7V3c0-2.2-2.3-3.7-4.3-2.7zM76.5 203.8l61.8-30.9c1-.5 1.7-1.5 1.7-2.7v-66.3c0-1.1-.6-2.2-1.7-2.7L76.5 70.3c-2-1-4.3.5-4.3 2.7v128.1c0 2.2 2.3 3.7 4.3 2.7z"></path>
</svg>
```

**Comment by Alhadis** [comment]
Done. =) New icon requests should be submitted to [`file-icons/source`](https://github.com/file-icons/source/issues) in the future, though. ;-)

The site's [docs](https://browsersync.io/docs/command-line) also mention the use of `browser-sync.js`, so I've included that too. Oddly, it didn't mention `bs-config.js` anywhere, although their [wiki does](https://github.com/BrowserSync/browser-sync/wiki/Working-with-a-Config-File).
