### ISSUE TITLE
Checklist icon for .todo files

### ISSUE THREAD

**Issue by eboracus** [file-icons/atom#663]
I see the package recently gained support for `.todo.txt` files, it would be nice to add icon support for `.todo` (and `.taskpaper`) files as well, using the octicon [checklist icon](https://octicons.github.com/icon/checklist/). I've added the todo file type locally in the past and used this icon in yellow which seemed to fit pretty well, in my opinion.

Particularly useful for those who (like me 😁) use the [atom-tasks](https://github.com/irrationalistic/atom-tasks) package which supports [these two](https://github.com/irrationalistic/atom-tasks#tasks-package) file types.

**Edit:** Is this the main location where the addition should go now:
https://github.com/file-icons/atom/blob/f26af76014403cda8c97cbc79597fa480d0f47d2/config.cson#L783-L789
Things have changed since I last forayed into the code of this package, was going to submit a PR, but wasn't familiar with the re-organisation, is more than one file modification needed(?)

**Comment by Alhadis** [comment]
Hey @eboracus,

Yeah, the package's structure was completely redesigned in [v2.0.0](https://github.com/file-icons/atom/releases/tag/v2.0.0). We now use a config file for managing the filetype-to-icon mappings, which is exactly what you've pointed to.
