### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by jdswee** [file-icons/atom#666]
<img width="1007" alt="2017-10-29 11 11 26" src="https://user-images.githubusercontent.com/8997423/32145134-89ebffa4-bcfe-11e7-81e2-6e7e0fdc6330.png">
anybody knows what happened? thanks

**Comment by Alhadis** [comment]
1. Please don't screenshot text when copy-paste will do.

2. The last line says:
~~~
Please include the following file with any support request:
~~~

But you haven't given us the file.

3. Try installing again, because it's probably just a connectivity problem.

**Comment by jdswee** [comment]
ok, thanks, i will try again
