### ISSUE TITLE
Creating directory and then delete it and create a file with the same name there is a small glitch

### ISSUE THREAD

**Issue by papallas** [file-icons/atom#667]
Ubuntu 14.04
Atom 1.20.1 x64
file-icons 2.1.13

This is a minor problem.

### Steps to reproduce

1. Open Atom with tree view open and a folder `A` expanded to see its files.
2. Open a file manager (i.e nautilus) and go to folder `A` and create a new folder/directory with name `test` using right-click -> new folder.
3. You should see the new folder appearing in the tree-view with the folder icon correctly shown there.
4. Go back to nautilus and delete the folder/directory.
5. Right-click -> new empty document and name it `test`.
6. Check tree view you should see wrongly the file having a folder icon and after some seconds to become a correct file icon.

![test](https://user-images.githubusercontent.com/6514550/32499632-01e28550-c3cb-11e7-9c6d-6a4f5f7d532a.gif)

See the above gif. The icon after a while reset into a normal document icon although not shown in the gif above. Moreover, it looks like file-icons bug because Atom treats the change as file (the expand arrow is missing as you can see which means that when I created the test empty file this expand arrow from the three view disappear).

**Comment by Alhadis** [comment]
👋 Hey @papallas, sorry for the slow response,

This is a known issue with filetypes (where "filetype" means "directory", "regular file", "symbolic link", etc). Closing this in favour of #490; please subscribe there for updates.
