### ISSUE TITLE
Add an icon for .webmanifest

### ISSUE THREAD

**Issue by jaydenseric** [file-icons/atom#668]
It's the emerging standard file extension for web app manifests: See [the spec](https://www.w3.org/TR/appmanifest/#media-type-registration).

It currently has no icon 😢

<img width="173" alt="screen shot 2017-11-08 at 7 13 08 pm" src="https://user-images.githubusercontent.com/1754873/32538089-f3328f5c-c4b8-11e7-893b-16fb0d2d44aa.png">

**Comment by Alhadis** [comment]
Hrm, would JSON's icon be appropriate?

**Comment by jaydenseric** [comment]
Yep! The mime type is `application/manifest+json`.

**Comment by Alhadis** [comment]
Done, thank you!
