### ISSUE TITLE
allow hiding explorer arrows via icon theme

### ISSUE THREAD

**Issue by coderafei** [file-icons/atom#669]
https://github.com/Microsoft/vscode/pull/35856

here is new feature in v1.18.0

**Comment by Alhadis** [comment]
Not related to this package. Also, VSCode has a completely different implementation of icons, to my understanding.

If you want to hide the arrows in the `tree-view`, simply [add this to your stylesheet](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks):

~~~css
.list-tree.has-collapsable-children .list-nested-item > .list-item::before{
	visibility: hidden;
}
~~~
