### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by ilanbiala** [file-icons/atom#67]
The package seems to be quite slow compared to other Atom packages. Is there anything that can be done about performance?

`This package added 243ms to startup time.`

**Comment by ear1grey** [comment]
I'm currently it take 10x the time of other pieces (OSX 10.11.3 Atom 1.6.2) - is there a debug switch I can flip on?
<img width="409" alt="screenshot 2016-04-04 11 14 06" src="https://cloud.githubusercontent.com/assets/409687/14245061/9a89bdea-fa56-11e5-8042-d8c84d44aa29.png">

**Comment by Alhadis** [comment]
Hrm, really? That's strange, because the package is hardly even taking 19ms to load for me...

<img width="367" alt="19ms" src="https://cloud.githubusercontent.com/assets/2346707/14259691/5cba9f94-faeb-11e5-8409-e809466f348d.png">

And in Timecop:
<img src="https://cloud.githubusercontent.com/assets/2346707/14259802/f0e97852-faeb-11e5-86ae-ae75839ea9dc.png" width="340" />

**Comment by ear1grey** [comment]
I think I've tracked down the culprit - an intermittent DNS fault from my ISP _may_ have been introducing the delay to the startup.  Switching to Google's Public DNS (8.8.8.8 / 8.8.4.4) reduces startup to 13ms for me too, so _possibly_ something to look at for async startup in the future, but in the mean time this may help someone.
<img width="238" alt="screenshot 2016-04-11 11 45 17" src="https://cloud.githubusercontent.com/assets/409687/14424815/1b443292-ffdb-11e5-95e0-ea27c54c46a4.png">

**Comment by Alhadis** [comment]
Bizarre. Maybe the [metrics package](https://github.com/atom/metrics) had something to do with it? It might've been trying to report the startup times or something...

**Comment by iovis9** [comment]
It's taking 578ms to load for me (next one is 57ms). How should I debug this?

**Comment by Alhadis** [comment]
@iovis9 Is this happening on multiple reboots?

On first load, the package needs to compile the Less sheets if they've changed (which it will if there's been an update released).

(Note this delay won't happen in V2)

**Comment by iovis9** [comment]
It's been happening over the course of at least 5 months.

**Comment by Alhadis** [comment]
What other packages do you have installed? Specs, operating system?

**Comment by iovis9** [comment]
OS X 10.11.6
Atom 1.9.9

```
Built-in Atom Packages (89)
├── about@1.5.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.0
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.39.0
├── find-and-replace@0.198.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.0
├── language-csharp@0.12.1
├── language-css@0.36.2
├── language-gfm@0.86.0
├── language-git@0.13.0
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.22.0
├── language-javascript@0.119.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.52.0
├── language-shellscript@0.22.3
├── language-source@0.9.0
├── language-sql@0.21.1
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.8
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.1
├── metrics@0.53.1
├── notifications@0.64.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.2
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.2
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.238.2
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.47.1
├── symbols-view@0.113.0
├── tabs@0.98.1
├── timecop@0.33.1
├── tree-view@0.208.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (50) /Users/david/.atom/packages
├── Zen@0.16.4
├── advanced-open-file@0.16.4
├── atom-autocomplete-php@0.18.9
├── atom-beautify@0.29.11
├── atom-ctags@4.5.2
├── atom-html-preview@0.1.22
├── atom-material-syntax@0.4.6
├── atom-material-syntax-dark@0.2.5
├── atom-material-ui@1.3.6
├── autocomplete-paths@1.0.2
├── autocomplete-python@1.8.6
├── autocomplete-sass@0.1.0
├── base16-ocean-dark-syntax@1.0.1
├── bezier-curve-editor@0.7.2
├── color-picker@2.2.2
├── docblockr@0.8.4
├── emmet@2.4.3
├── ex-mode@0.13.0
├── file-icons@1.7.19
├── git-plus@5.16.2
├── git-time-machine@1.5.3
├── golden-ratio@0.3.0
├── highlight-line@0.11.1
├── highlight-selected@0.11.2
├── language-nginx@0.6.1
├── language-rspec@0.5.0
├── linter@1.11.16
├── linter-csslint@1.3.2
├── linter-js-yaml@1.2.5
├── linter-jshint@2.1.0
├── linter-pep8@1.3.0
├── linter-php@1.2.0
├── linter-phpmd@1.5.0
├── linter-rubocop@0.4.7
├── linter-scss-lint@3.0.4
├── linter-tidy@2.2.0
├── linter-xmllint@1.3.5
├── merge-conflicts@1.4.4
├── minimap@4.24.7
├── minimap-pigments@0.2.1
├── open-terminal-here@2.1.4
├── pigments@0.34.0
├── project-manager@2.9.7
├── rails-snippets@2.7.0
├── relative-numbers@0.5.1
├── sort-lines@0.14.0
├── tab-control@0.6.9
├── tablr@1.5.0
├── toggle-quotes@1.0.0
└── vim-mode@0.65.1

└── (empty)
```


![screen shot 2016-08-29 at 11 34 54](https://cloud.githubusercontent.com/assets/6660202/18047335/af9e5c8c-6ddc-11e6-8bd9-81da0f45ebb4.png)

**Comment by iovis9** [comment]
Dammit, I thought this repo was `linter-php`. I'm having worse problems with them.
A restart of the app now makes it load faster, you're right.

**Comment by Alhadis** [comment]
Well, that issue won't exist in V2 either way, which uses a config-driven approach instead of a CSS-driven one. :)
