### ISSUE TITLE
More comprehensive contributing guidelines

### ISSUE THREAD

**Issue by jthegedus** [file-icons/atom#670]
Firstly, thanks for the awesome icons!

I want to add a new icon to the repo but would rather create a PR than a request. The guidelines say that adding new icons are done in the [source repo](https://github.com/file-icons/source#adding-new-icons). Must I wait for a PR there to be accepted and merged before I can make the file association here? Or can I optimistically create a PR here before the icon is actually merged there?

Answering these questions here so I can get started would be good, but updating the guidelines for future contributors about this process would be ideal. Also referencing the Contributor guidelines in the README would make it more discoverable than just having the file in the repo.

**Comment by Alhadis** [comment]
:wave Hey @jthegedus,

Originally, there was more information in the source repo on how to add a new icon. However, I took it down because every icon gets cleaned up and optimised by hand using Adobe Illustrator, making the regeneration process moot.

I intend to develop a more streamlined process someday, but at this point, I can't say when. I've updated the contributor docs with something more substantial, however.

**Comment by jthegedus** [comment]
@Alhadis thanks for the update :)

**Comment by Alhadis** [comment]
No worries, sorry about the slow response. 👍

**Comment by jthegedus** [comment]
No need to apologise :smile:

**Comment by Alhadis** [comment]
@jthegedus Just a heads up to inform you I'll be cutting another release in a few days, so better to get this icon added sooner rather than later. ;)

**Comment by jthegedus** [comment]
@Alhadis I'll have time to look at your changes and work on this in 36hrs or so. Hopefully that's soon enough :)

**Comment by Alhadis** [comment]
Could you perhaps tell me which icon you'd like added instead? It's easiest that way.

**Comment by jthegedus** [comment]
Sure! It's the [Prettier logo](https://github.com/prettier/prettier-logo/pull/3/files). It's an SVG modified by me of the original and is approved (but yet to be merged) by the Prettier people. I've recommended that users of the icon [add a transform to this svg group](https://github.com/PKief/vscode-material-icon-theme/pull/138/files#diff-42a2ee888f71eebec8db8c9407a36f71R10) should they require any scaling/transform to better fit with their icon set. [This PR](https://github.com/PKief/vscode-material-icon-theme/pull/138) shows the math for recentering the icon based off the scale factor.

These are the supported file names:
```
.prettierrc
.prettierrc.js
.prettierrc.json
.prettierrc.yaml
.prettierrc.yml
prettier.config.js
```
I thought a PR would be more friendly is all. Cheers for your work :smiley:
