### ISSUE TITLE
No icons on opened files?

### ISSUE THREAD

**Issue by wojlive** [file-icons/atom#672]
Hi,

When file is being opened there is no icon next to it's name where the list of opened files are, how can I get it to show up?

![image](https://user-images.githubusercontent.com/29060712/32775879-a182e070-c928-11e7-96d2-98eaaf2d61e8.png)

Also is It possible in navigation to color the text to it's corresponding icon i.e php icon = blue text

Thanks!

**Comment by Alhadis** [comment]
> When file is being opened there is no icon next to it's name where the list of opened files are, how can I get it to show up?

Are you referring to the icons in the tab pane, above the editor?

![figure-1](https://user-images.githubusercontent.com/2346707/32776153-c14a0818-c985-11e7-9a54-1ef4d119640a.png)

If so, check the status of the package's **"Show icons in file tabs"** setting. It should be enabled:

<img src="https://user-images.githubusercontent.com/2346707/32776361-69d95fa6-c986-11e7-8c80-d70abf7756d5.png" width="670" alt="Figure 2" />

> Also is It possible in navigation to colour the text to it's corresponding icon i.e php icon = blue text

It is possible, but you need to [use your stylesheet](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks):

~~~less
.tree-view{
	.light-red     { color: #c97071; }
	.medium-red    { color: #ac4142; }
	.dark-red      { color: #be2f31; }
	.light-green   { color: #b2c38b; }
	.medium-green  { color: #90a959; }
	.dark-green    { color: #66783e; }
	.light-yellow  { color: #fae0bc; }
	.medium-yellow { color: #f4bf75; }
	.dark-yellow   { color: #ee9e2e; }
	.light-blue    { color: #9dc0ce; }
	.medium-blue   { color: #6a9fb5; }
	.dark-blue     { color: #46788d; }
	.light-maroon  { color: #be7953; }
	.medium-maroon { color: #8f5536; }
	.dark-maroon   { color: #7c4426; }
	.light-purple  { color: #c7a4c0; }
	.medium-purple { color: #aa759f; }
	.dark-purple   { color: #825078; }
	.light-orange  { color: #e1ad83; }
	.medium-orange { color: #d28445; }
	.dark-orange   { color: #a35f27; }
	.light-cyan    { color: #a7d0c9; }
	.medium-cyan   { color: #75b5aa; }
	.dark-cyan     { color: #4d9085; }
	.light-pink    { color: #ff4ddb; }
	.medium-pink   { color: #ff00cc; }
	.dark-pink     { color: #cc00a3; }
}
~~~

**Comment by wojlive** [comment]
Awesome! You are a star! one last question, can the colour be applied also to the opened files? Thanks

**Comment by Alhadis** [comment]
Do you mean in the tabs? Yes, just update the first line of the CSS snippet I gave you:

~~~less
.tree-view, .tab-bar{
…
~~~

**Comment by wojlive** [comment]
Thank you very much for the help!
