### ISSUE TITLE
ChartJS icon shows for a plain js file that happens to be called chart.js

### ISSUE THREAD

**Issue by hally9k** [file-icons/atom#673]
I don't use ChartJS but I wonder if a file called `chart.js` should match here.
I'm assuming that this is an extension so `my-file-name.chart.js`
Should the regex not be changed from `^Chart(\.bundle)?(\.min)?\.js$`  to `^.*\.Chart(\.bundle)?(\.min)?\.js$`?
This bugs me probably more than it should... 
<img width="253" alt="screen shot 2017-11-16 at 12 48 10 pm" src="https://user-images.githubusercontent.com/3803536/32866905-ec7aee22-cace-11e7-9f42-cf5c973d852c.png">

**Comment by Alhadis** [comment]
👋 Hey @hally9k,

It isn't an extension, meaning it's supposed to match a file named `chart.js`. In hindsight, that probably wasn't very clever of me... 🤔

> This bugs me probably more than it should...

If it does, remember you have your stylesheet. ;) That's always going to have precedence:

~~~css
.icon[data-name="chart.js"]::before{
	color: #f4bf75;
	content: "\f129";
	font-family: Mfizz;
	font-size: 14px;
	top: 1px;
}
~~~

**Comment by hally9k** [comment]
Hey @Alhadis :)

I'm just interested, in what case does the ChartJS icon show up. Is it based on a file naming convention, or is it the ChartJS lib itself?

**Comment by Alhadis** [comment]
It's being matched by name. :) You can [see here](https://github.com/file-icons/atom/blob/9937f1e6c22b6b32b0b7f1c42fe31684d2f4437c/config.cson#L782-L786):

https://github.com/file-icons/atom/blob/9937f1e6c22b6b32b0b7f1c42fe31684d2f4437c/config.cson#L782-L786

**Comment by hally9k** [comment]
I understand it's matching by the file name. It's the use case in which the icon adds value to the coder I'm interested in.

**Comment by hally9k** [comment]
Is it supposed to denote a file that uses ChartJS?

**Comment by Alhadis** [comment]
No, it's supposed to denote the ChartJS library itself.

**Comment by hally9k** [comment]
Oh yes I see. IMO we should maybe consider removing this rule. I see little to no value in highlighting the lib itself whereas the incorrect icon for any file with a naming clash is a bit of a bad UX. It's likely to crop up quite often too I'd expect. My case being a JS file for a medical chart as one example.
Just my 2 cents any how.
Many thanks for all the work. This plugin is a core part of my atom setup 👍  💯

**Comment by hally9k** [comment]
At minimum we could make it case sensitive as the chart.js lib is actually `Chart.js` I think. Although it's a bit of a weak compromise IMHO.

**Comment by Alhadis** [comment]
Ideally, "problematic" cases like these should be resolved by checking the contents of the file and looking for a specific substring. Currently, that's not how things work... it could do with some revising.
