### ISSUE TITLE
Uncaught TypeError: Cannot create icon-node for empty path

### ISSUE THREAD

**Issue by WenChenWu** [file-icons/atom#685]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.14

### Stack Trace

Uncaught TypeError: Cannot create icon-node for empty path

```
At C:\Users\Edward\.atom\packages\file-icons\lib\service\icon-node.js:174

TypeError: Cannot create icon-node for empty path
    at Function.forElement (/packages/file-icons/lib/service/icon-node.js:174:11)
    at /packages/file-icons/lib/service/icon-service.js:80:31)
    at IconServices.updateMRUIcon (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/tabs/lib/get-icon-services.js:59:50)
    at MRUItemView.initialize (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/tabs/lib/mru-item-view.js:67:51)
    at MRUListView.buildListView (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/tabs/lib/mru-list-view.js:200:24)
    at ~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/tabs/lib/mru-list-view.js:121:46
```

### Commands

```
     -0:48.5.0 intentions:highlight (input.hidden-input)
     -0:48.5.0 core:save (input.hidden-input)
     -0:48.2.0 editor:newline (input.hidden-input)
     -0:45.9.0 intentions:highlight (input.hidden-input)
     -0:45.8.0 core:undo (input.hidden-input)
     -0:43.6.0 core:move-down (input.hidden-input)
     -0:43.1.0 editor:newline (input.hidden-input)
  3x -0:40.6.0 core:backspace (input.hidden-input)
     -0:28.9.0 editor:newline (input.hidden-input)
     -0:26.7.0 autocomplete-plus:confirm (input.hidden-input)
  5x -0:23.1.0 core:backspace (input.hidden-input)
     -0:20.9.0 intentions:highlight (input.hidden-input)
     -0:20.7.0 core:save (input.hidden-input)
     -0:17.9.0 intentions:highlight (input.hidden-input)
     -0:17.7.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:16.5.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-color-the-tag-name 1.14.0 
atom-jade 0.3.0 
atom-live-server 2.2.0 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
expand-selection-to-quotes 0.11.0 
file-icons 2.1.14 
fold-navigator 0.0.620 
intentions 1.1.5 
language-pug 0.0.21 
linter 2.2.0 
linter-js-standard 4.1.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
pigments 0.40.2 
teletype 0.3.0 
```

**Comment by nicholascapo** [comment]
This happens to me when i use Ctrl-Tab to switch between open files.

**Comment by Alhadis** [comment]
Confirmed with a vanilla Atom install and a blank file tab. I must have missed this because I have the MRU feature disabled... sorry guys. 😞  Will push a hotfix for this.

**Comment by nerochiaro** [comment]
The fix hasn't made it to the deb packages released at https://atom.io/download/deb yet, a month after the fix has been committed. Can we please have a release that includes this, as it's breaking tab switching for those who use the keyboard to do so.

**Comment by Alhadis** [comment]
Holy shit, did I seriously forget to cut a release too? 😥  Okay, that's seriously bad. Doing this now.

**Comment by Alhadis** [comment]
Okay, sitting down to have a closer look at this confirms I *did* cut a `file-icons` release that includes this fix after all. @nerochiaro, what exactly are you having problems with?

**Comment by nerochiaro** [comment]
When I posted the comment I had just installed the deb package for 1.23.3, and pressing ctrl+tab would display the error message. Even restarting atom did not fix the problem.

But I tried again today, and everything seems to work OK. I have no idea why it would do that just after the update.

Sorry for the noise @Alhadis.
