### ISSUE TITLE
MATLAB icon is not visible

### ISSUE THREAD

**Issue by fepegar** [file-icons/atom#686]
Hello,

I've seen there is an SVG for MATLAB, but on my Atom my `.m` files are assigned the (default?) "@{" icon.

**Comment by Alhadis** [comment]
👋  Hey mate,

The `.m` extension is used by both MATLAB and Objective-C. The `@{` icon you're seeing is the icon used for Objective-C files. If you prefer `.m` files be used for MATLAB instead, you can register it as a [custom filetype](http://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition). Just add the following to your `config.cson` file:

~~~cson
"*":
	core:
		customFileTypes:
			"source.matlab": [
				"m"
			]
~~~

**Comment by fepegar** [comment]
Worked like a charm. Cheers!

**Comment by Alhadis** [comment]
Good to hear! =)

**Comment by fepegar** [comment]
Reference for myself:

If you get indentation errors, just put everything in one line
```cson
customFileTypes: "source.matlab": ["m"]
```
