### ISSUE TITLE
Wrong file assignment

### ISSUE THREAD

**Issue by mbuc82** [file-icons/atom#690]
Hello together,

since one update, at least the file assignments for perl files (*.pl / *.pm) are wrong obviously. Those files display the onion sign instead of the camel. 

I know it's a small issue, but it would be nice, if you could fix it :)

Thanks in advance!

**Comment by Alhadis** [comment]
Add the following ruleset to your stylesheet:

~~~css
.perl-icon::before{
	content: "\f142";
	font-family: Mfizz;
	font-size: 14px;
	top: 1px;
}
~~~

The onion isn't "wrong", it's the logo of The Perl Foundation. Moreover, it's clearer and easier to distinguish at icon-size than a camel, hence why I chose it.
