### ISSUE TITLE
Icon Request: TypoScript

### ISSUE THREAD

**Issue by atomicptr** [file-icons/atom#699]
Not to confuse with Typ**e**Script!

- File endings: **.typoscript** / **.tsconfig**
- DevOpicons actually has the TYPO3 logo available with "\e672" 
![image](https://user-images.githubusercontent.com/674705/35336558-1ed3a3de-0119-11e8-8fe4-dfcedb9b3f9a.png)

- Color: [#FF8700 is their CI color](https://typo3.org/about/the-brand/style-guide/the-typo3-colors/), though any orange would probably suffice

tyvm

**Comment by Alhadis** [comment]
It took all my effort not to make a typo on purpose while adding this.

Thanks!
