### ISSUE TITLE
Feature request: "git-ignored" files styling

### ISSUE THREAD

**Issue by JonatasAmaral** [file-icons/atom#705]
I'm suggest to add a style for icons of a _git-ignored_ file or inside of a _git-ignored_ folder, to turn the icon gray or turn down it's opacity, like so:

```
.status-ignored .icon:before{
	opacity: 0.5;
}
```

I can do it in my `~/.atom/styles.less` (and i did it), but it would be better if this come in package by default

**Comment by Alhadis** [comment]
> I can do it in my `~/.atom/styles.less` (and i did it), but it would be better if this come in package by default

Sorry, but no. That's what your stylesheet is for. :wink:

**Comment by JonatasAmaral** [comment]
ok. But i think it is a kite useful (and simple) think to not come by default in the package (there is some others that do it)
This way, we don't need to re-set it on every new installation (new computers)[or backup the stylesheet just for it], and any user can have this feature
just a thought

**Comment by Alhadis** [comment]
Well, that logic doesn't add up because you'd have to back your `~/.atom/config.cson` file anyway (which shares the same directory as your stylesheet: `~/.atom/style.less`).

If we add a setting to do what CSS is supposed to do, we may as well add one for every other property that users are likely to change: `color, `font-size`, `margin-top`, `margin-left`, `line-height`, and `opacity`. See the problem?

**Comment by JonatasAmaral** [comment]
i didn't understood why add any other property, i'm a bit confused

What i'm suggesting is to differentiate the icon from files that was ".gitignored" from those that didn't. Anything that better fits the project layout and appearance
Make those icons gray or a bit transparent, and even use the ".status-ignored" css selector was a suggestion (i'm not an advanced guy, so i don't even understand how does this package in managed)
But could be anything that easily identify ignored files, as well the icons make it ease do identify the file type. For example, make the icon be an "closed eye" (as "prepros" do to its _not watching_ files)

Just thought that, for majority, identify ".gitignored" files rapidly is almost as important as its file type
So i thought that i would be nice get it by default
