### ISSUE TITLE
*.js files being recognized as *.jsx files

### ISSUE THREAD

**Issue by lpaulger** [file-icons/atom#711]
Since the most recent update, icons for *.js has started being recognized as *.jsx (see below)

<img width="224" alt="screen shot 2018-02-22 at 12 06 41" src="https://user-images.githubusercontent.com/1000544/36532392-4520e30a-17c9-11e8-948e-bf27205c9ed2.png">

**Comment by Alhadis** [comment]
I'm only an hour away from [releasing a patch](https://github.com/file-icons/atom/blob/72c5e3d06df526d10748ab68c6b1342ac29a9a21/CHANGELOG.md#change-log) for this. :wink: Hold your horses, mate.

In the meantime, you can have a read through the original issue which you're the fifth person to duplicate. :disappointed:

(The entire Atom world must be so confused right now...)
