### ISSUE TITLE
.tipe file icon

### ISSUE THREAD

**Issue by gdi2290** [file-icons/atom#714]
https://tipe.io
Here's the logo. You may need to convert the blue to white and remove the gradient  
<img src="https://cdn.tipe.io/tipe/tipe-1024x1024.png">

**Comment by Alhadis** [comment]
Hey @gdi2290, sorry about the slow response.

What filenames or extensions should this icon be displayed for? (For future references, new icon requests should be submitted to the [`file-icons/source`](https://github.com/file-icons/source) repository. 😉)

**Comment by Alhadis** [comment]
Never mind, I'm a moron. :sweat_smile: You put the filename in the issue's title, and I didn't even notice.

**Comment by gdi2290** [comment]
awesome I can't wait to see it 🎉
have you considered adding this project to [opencollective](https://opencollective.com)?

**Comment by Alhadis** [comment]
I've never heard of it. What's OpenCollective?

**Comment by Alhadis** [comment]
... right, gonna do this OpenCollective thing. Normally I can't stand asking for charity, but I'm broke, have no Adobe Subscription anymore (so I'm fumbling around very slowly in Inkscape instead), and worst of all, an old laptop running an OS that lacks Electron/Atom support.

So yeah, having a shiny MacBook would actually make my ability to contribute to my own projects 1000% times more effective. 🤣

**Comment by Alhadis** [comment]
[Here you are](https://opencollective.com/file-icons/). Knock yourself out. 😁

Not really sure what to expect from this, but hey.

**Comment by gdi2290** [comment]
@Alhadis backed. can you put our logo in your readmes with a link to our website 👍

**Comment by Alhadis** [comment]
Wow, thanks! And most certainly! :D Will do so once I'm at a computer again (editing on GitHub with a smartphone tends not to go so well...)
