### ISSUE TITLE
Installaiton Error

### ISSUE THREAD

**Issue by SawHtoo** [file-icons/atom#717]
First I install from editor. This error is appear
![error](https://user-images.githubusercontent.com/12810256/37451823-2d72b866-2861-11e8-860f-c92c8ae3ea35.PNG)
And I also try to install from command line
![error1](https://user-images.githubusercontent.com/12810256/37451865-56dc824a-2861-11e8-86ba-e548ab530634.PNG)

**Comment by Alhadis** [comment]
@SawHtoo Try following [these steps](https://github.com/file-icons/atom#installation-halts-with-an-npm-error), then try again:

~~~bash
rm -rf ~/.atom/.apm
apm install --production file-icons
~~~

**Comment by SawHtoo** [comment]
That is Linux command. I use Windows version.

**Comment by SawHtoo** [comment]
Can I delete it from directory? but there are other packages that I've installed.
![ss](https://user-images.githubusercontent.com/12810256/37452489-235d50f0-2863-11e8-83dd-473d5a50ed93.PNG)

**Comment by Alhadis** [comment]
Do yourself a favour and install [GOW](https://github.com/bmatzelle/gow/releases). GNU tools for Windows, very minimal install size (as opposed to a behemoth like Cygwin).

But yeah, just delete the `.apm` folder and try again.

**Comment by Alhadis** [comment]
> but there are other packages that I've installed.

Oh sorry,  missed that second part.

The `.apm` folder is actually just a cache for downloaded package dependencies (the same way `.npm` is used for caching downloaded modules). The actual packages are stored in the `packages` directory. Deleting `.apm` will force Atom to redownload dependencies when installing.

This can sometimes be necessary if your connection dropped out while installing, and you were left with half a download in `.apm`.

**Comment by SawHtoo** [comment]
Thanks a lot @Alhadis
