### ISSUE TITLE
'Change on grammar override' not working

### ISSUE THREAD

**Issue by AdmiralShinysides** [file-icons/atom#727]
I have 'Change on grammar override' checked and have added a file extension to my 'customFileTypes' section of my 'config.cson' except the file-icons for those extensions will not update in either the active tab or the project tree view.

Attached image shows my 'config.cson' with the 'customFileTypes' set, as well as the 'rdg' extension following my syntax-highlight change, but the file-icons are still for an unsupported file type.

![capture](https://user-images.githubusercontent.com/38766488/39487281-4a0cf7c2-4d44-11e8-8072-a4dc322084b9.PNG)

**Comment by Alhadis** [comment]
👋Hey @AdmiralShinysides,

I'll have a look into this. What are you expecting to see instead of an icon of an empty paper?

**Comment by Alhadis** [comment]
Also, what packages and themes do you have installed?

And what are `*.rdg` files?

**Comment by AdmiralShinysides** [comment]
If I'm reading the setting right in the 'file-icons' package settings, because I am manually telling 'rdg' files to follow the language of 'xml' files, I should see the file-icon change to the icon used by 'xml'

![image](https://user-images.githubusercontent.com/38766488/39489576-a5d8e096-4d4b-11e8-82d0-dc1ca5e073b8.png)

**Comment by Alhadis** [comment]
Ah, now I see what's going on here. You've been doing all the steps correctly, well-done.

Certain formats like XML or JSON were deemed earlier in the project to be [too commonplace](https://github.com/file-icons/atom/blob/master/config.cson#L45).

However, the importance of this isn't clear and difficult to explain for some people, so I think this file-format could do with some improvement... -_-

**Comment by AdmiralShinysides** [comment]
That does the trick, thank you for the quick responses, @Alhadis !

**Comment by Alhadis** [comment]
And thank *you* for your patience and help. ;) Particularly the help you're about to give me...

GitHub is indexing [3,015 unrecognised](https://github.com/search?q=extension%3Ardg+NOT+nothack&type=Code) code files which use the `.xdg` extension. I don't know what the format is used for, could you give me some links so I can get this recognised and registered at [Linguist](https://github.com/github/linguist)? =)

**Comment by Alhadis** [comment]
I managed to misspell `.rdg` as `.xdg` *every single time* in this thread, even when I committed the change. :|

3-LETTER WORDS ARE HARD WORK, YOU GUYS
