### ISSUE TITLE
Change Go icon to match their new redesigned logo

### ISSUE THREAD

**Issue by AppIns** [file-icons/atom#728]
Go has a new logo and I was wondering if we could change the Gopher to the new theme.

https://blog.golang.org/go-brand

**Comment by Alhadis** [comment]
Grrr... 😥I've a gut feeling users are gonna prefer the old icon:

<img src="https://user-images.githubusercontent.com/2346707/39632357-3804c40e-4ff8-11e8-807c-410a751a7743.png" alt="Figure 1" />

Those who do need only add the following CSS to their stylesheets:

~~~less
.go-icon:before{
	content: "\e624";
	font-size: 15px;
	left: auto;
	top: 3px;
}
~~~

**Comment by AppIns** [comment]
@Alhadis  :+1:
