### ISSUE TITLE
Is this a bug or is my env messed up?

### ISSUE THREAD

**Issue by afgallo** [file-icons/atom#729]
![image](https://user-images.githubusercontent.com/9999415/39562066-e7695246-4eec-11e8-9577-289f32b82bfe.png)

See image above. My expectation was to have the same icon for my `.vue` files. This may well be a problem with my current set-up so any advice will be appreciated.

Cheers!

**Comment by Alhadis** [comment]
👋 Hi @afgallo,

Did you manually set the file's language to JSX? The package will update the icons for files whose grammars are specified by the user. Open the [grammar selector](https://github.com/atom/grammar-selector) and choose **Auto-detect** at the top of the list:

<img src="https://user-images.githubusercontent.com/2346707/39615302-bc83ceea-4fb8-11e8-9483-047a191b875e.png" width="375" alt="Figure 1" />

You should then see the icon change back to the Vue icon. If not, follow [these steps](https://github.com/file-icons/atom#an-icon-has-stopped-updating).

You can also turn this feature off by unchecking **Change on grammar override** in the package settings:

<img src="https://user-images.githubusercontent.com/2346707/39615656-c8ac812e-4fba-11e8-9a57-7b893c345914.png" width="422" alt="Figure 2" />

**Comment by afgallo** [comment]
Hi @Alhadis, I think it must have been a glitch after installing the plugin. When I opened up Atom this morning it was all good.

Cheers for the help.
