### ISSUE TITLE
.DS_Store icon style

### ISSUE THREAD

**Issue by niccolomineo** [file-icons/atom#733]
Hey man, thanks for the great package! What about making the MacOS icon more vibrant?

![schermata 2018-05-09 alle 16 44 48](https://user-images.githubusercontent.com/5409469/39821367-5dce643e-53a8-11e8-89e9-0400a814a97f.png)

**Comment by Alhadis** [comment]
What do you mean by vibrancy? Colours? Contrast? Slightly larger icon display?

**Comment by niccolomineo** [comment]
Yes, colour-wise.

**Comment by Alhadis** [comment]
In your stylesheet, add a rule for targeting desktop services stores (`.DS_Store` files):

~~~less
.finder-icon:before{
	color: #6a9fb5;
}
~~~

You might ned to play with the HSV levels before you find a satisfactory shade for the icon.

If there's anything else I can do to help, please ask. 👋

**Comment by niccolomineo** [comment]
That's so much better already. Thanks a lot.

**Comment by Alhadis** [comment]
My pleasure!
