### ISSUE TITLE
.spec icon only shows up if containing folder named 'test'

### ISSUE THREAD

**Issue by taygrave** [file-icons/atom#734]
We are moving to [colocate our test files](https://medium.com/@alexmngn/how-to-better-organize-your-react-applications-2fd3ea1920f1) within our main component directories, vs. in a separate 'test' folder, however I have noticed that the .spec icon no longer renders when tests are not located under an explicitly named 'test' directory. Please update the .spec icon to render even outside of an explicit 'test' folder.

**Comment by Alhadis** [comment]
Hi @taygrave,

Sure thing, but we'll need some sort of common extension or filename prefix to distinguish them unambiguously as tests. What filenames are you currently using?

**Comment by taygrave** [comment]
isn't the `<fileName>.spec.js` suffix enough to indicate they are unit test files? what else might they be? I thought that's what it meant.

**Comment by Alhadis** [comment]
Well the icons were originally applied to *all* script files located in a recognised spec-directory. I then realised it's common to include helper files like `spec/helpers.js` which shouldn't share the same test-icon.

Somehow along the way I managed to totally overlook a simpler use like the one you're recommending. =) Will fix.

**Comment by Alhadis** [comment]
There were *a lot* of files that needed optimising in the same way. o0;

Should all be good now.

**Comment by taygrave** [comment]
Wonderful, thanks so much - I assume this will be included in the v2.1.21 update? ETA on that version's release? :)

**Comment by Alhadis** [comment]
ETA is [15 hours ago](https://github.com/file-icons/atom/commit/79a848633b73e0a7f8793e37a98eef64603e43e8). 👍

**Comment by taygrave** [comment]
oh sweet! Atom must be processing it or something atm - isn't displaying the update yet. Thanks again!

**Comment by Alhadis** [comment]
Try uninstalling and reinstalling. :wink:
