### ISSUE TITLE
Incorrectly styled font with every Ruby file

### ISSUE THREAD

**Issue by Vincentdc94** [file-icons/atom#739]
Hello there,
I found a bug in your extension and researched a bit already for you guys.

Clearly the text behind the icon doesn't match the font it should show.
![Incorrectly renderend fonts](https://user-images.githubusercontent.com/4875955/40267919-1829d17e-5b65-11e8-9ea4-974a6bd79c37.png)

I went on research and unchecked these two style rules, and the fonts where styled correctly.
![Css rules that cause the problem](https://user-images.githubusercontent.com/4875955/40267899-ee648cf8-5b64-11e8-9f53-84f19aaa9efd.png)

The result was as it should be as you see on the image below
![This is how it should be](https://user-images.githubusercontent.com/4875955/40267970-c7181038-5b65-11e8-8553-ff73a3c2b787.png)

I tried to look in the code but didn't find a direct solution. I only checked the .less files tough and I have to work on the project that is open in atom so I only spend a few minutes and decided to post it here.

**Extra info**
- I run Ubuntu 18.04 64bit, Gnome 3
- Atom version is 1.26.1
- File icons extension version is 2.1.21 but the issue was already present in previous version.

If you need any other info, feel free to ask! I hope this will already help you further.

**Comment by Alhadis** [comment]
Uninstall `language-etherum`. It's a [known issue](https://github.com/file-icons/atom/issues/708#issuecomment-369521612) with that particular package.

Its author has been contacted to merge an [upstream pull-request](https://github.com/caktux/language-ethereum/pull/13), but there's been no response. The only solution is to use another package for Ethereum highlighting.

**Comment by Alhadis** [comment]
I'm actually going to update the troubleshooting docs to explain this, because you're not the first person to report this. I doubt you'll be the last, either...
