### ISSUE TITLE
.mjmlslim file extension

### ISSUE THREAD

**Issue by kapso** [file-icons/atom#741]
It will be nice to see file icon for `.mjmlslim`

Existing icon for `.mjml` should work https://github.com/file-icons/atom/blob/429ac5e6cca6b8e532e23d673eca13579335c0a4/lib/icons/.icondb.js#L913

**Comment by Alhadis** [comment]
No problem, added. Thanks!

**Comment by kapso** [comment]
That was quick, thanks a lot 👍
