### ISSUE TITLE
Add .isml icon

### ISSUE THREAD

**Issue by Unikalx** [file-icons/atom#742]
Hello could you please add icon to .isml format.

**Comment by Alhadis** [comment]
Hey mate, :wave:

Could you please tell us about what the `.isml` format is for or used by? Some links to official documentation?

**Comment by Unikalx** [comment]
Hey
Here is a [link,](https://documentation.demandware.com/DOC2/index.jsp) but you can not see the information without an account, that's the screenshots from the link
[screen 1](http://prntscr.com/jzxmej)
[screen 2](http://prntscr.com/jzxmnl)
[screen 3](http://prntscr.com/jzxmxn)
[screen 4](http://prntscr.com/jzxn5y)
[screen 5](http://prntscr.com/jzxngz)
[screen 6](http://prntscr.com/jzxnr7)
Here is an example [code](http://prntscr.com/jzxr0p)

ISML very similar to HTML and is used for markup on the platform salesforce

**Comment by Alhadis** [comment]
Thanks!

Well I can add it, it's just a matter of which icon is most appropriate. Unless you can think of something better-fitting, I guess using a Salesforce icon is the way to go here? :thinking:
