### ISSUE TITLE
directory icon shown as file extension

### ISSUE THREAD

**Issue by AnthonyNTK** [file-icons/atom#743]
### Env:
Windows 10
Atom: 1.28.0
File-icons: 2.1.21

### Actual Behavior:
Some of the `folder icon` shows as `javascript icon`

### Expected Behavior:
The 'folder icon' represents all directories (just like the others as shown in the below picture).

![image](https://user-images.githubusercontent.com/26246071/41859712-5aa3af8e-78cf-11e8-9cb2-4fdeb783f759.png)

**Comment by Alhadis** [comment]
This can happen as a result 3

**Comment by AnthonyNTK** [comment]
Anything needed from me to have better understanding on such situation?

**Comment by Alhadis** [comment]
Did you delete a file named `ProfileButton` and created a directory for it instead, also named `ProfileButton`? That's also a known issue to be fixed.

In the meantime, when something weird happens that affect numerous icons in an awfully noticeable way, follow [these steps] (https://github.com/file-icons/atom/blob/master/README.md#an-icon-has-stopped-updating).

**Comment by AnthonyNTK** [comment]
I am pretty sure that that particular ***two*** directory was shown correctly _**yesterday**_ and for most of the time I remembered. I did follow the steps you provided and no luck....

For the delete situation, I may need to recheck my repo commit history but I am pretty sure that even it did happened, it would be like a month ago and more. I will give more info once I am free.

**Comment by Alhadis** [comment]
@AnthonyNTK Follow [those steps](https://github.com/file-icons/atom/blob/master/README.md#an-icon-has-stopped-updating) I mentioned earlier, then close and restart Atom. Your problem should have solved itself.

**Comment by AnthonyNTK** [comment]
I ended up manually deleting all atom related cache file in `%TEMP%` and those icons updated after restart.

**Comment by Alhadis** [comment]
Excellent. Good to hear that your problem is solved.

FYI, this is a known issue that's [been reported](https://github.com/file-icons/atom/issues/499) before. Going to close this now in an effort to reduce duplicate reports.
