### ISSUE TITLE
Webpack files not proper icons

### ISSUE THREAD

**Issue by EanKeen** [file-icons/atom#748]
Replacing webpack.config.js with webpack.common.js, webpack.dev.js, and webpack.prod.js (as per https://webpack.js.org/guides/production/) yielded an unexpected result.

Neither webpack.common.js, webpack.dev.js, nor the webpack.prod.js file had the proper Webpack file icon (which was associated with webpack.config.js).

Could the scope of the Webpack icon be changed to add these specific file names? I tried to add them manually, but avoided this as I did not want my changes to be overridden by an update.

**Comment by Alhadis** [comment]
Never mind. I realised it was silly to be cautious when Webpack can't stop changing its APIs anyway... :grin
