### ISSUE TITLE
Json specific icon

### ISSUE THREAD

**Issue by angrykoala** [file-icons/atom#749]
Hi, I have noticed that the `.json` icon is a bit "database" generic icon:
![screenshot from 2018-07-13 18-11-39](https://user-images.githubusercontent.com/5960567/42701957-3f89619c-86c8-11e8-8e20-20c0af58275c.png)

Would it be possible to use a more json-specific icon?, like the [json logo](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/JSON_vector_logo.svg/250px-JSON_vector_logo.svg.png) or the common [bracket icon](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTSdZjBgpqTiu5p0In6sbJDl_bvjX5BwDCSvhiEKJ3nmgwc_-k)

**Comment by Alhadis** [comment]
The JSON logo doesn't really work, I'm afraid. When you remove its gradients, it's nearly unrecognisable. Even with borders added, it looks closer to Chrome or Opera's logo:

<img src="https://user-images.githubusercontent.com/2346707/42724442-8fe29d28-87b5-11e8-86fc-189c889c3436.png" width="256" />

As for the brackets icon, well... we *could*. But that's a generic icon that isn't really format-specific. We try to avoid changing the icons of major formats unless there's a good reason to.

If you prefer the icon be changed, you can use your stylesheet to assign a different one:

~~~css
.icon[data-name$=".json"]::before{
	content: "";
	background: no-repeat 50% 50% url("/path/to/icon-file.svg");
	background-size: contain;
}
~~~

**Comment by angrykoala** [comment]
@Alhadis thanks for your answer and solution. fyi I think this svg version looks great

**Comment by Alhadis** [comment]
Well, thank you. :) I suppose it wouldn't hurt to add a few more "generic" icons to the package's icon range, just to give users an option to use different icons to the "generic" ones we have already. 🤔
