### ISSUE TITLE
Use ansible icon for source.ansible and source.ansible-advanced

### ISSUE THREAD

**Issue by brandonkal** [file-icons/atom#751]
I see that an ansible icon exists in this set. It looks like files must be named to either `site.ansible.yml` or `site.ansible` for the icon to take effect. It would be great if this package also matched the ansible icon to files whose source is ansible or ansible-advanced from the language-ansible package.
Thank you for the awesome package!

**Comment by Alhadis** [comment]
👋 Hey @brandonkal,

> It would be great if this package also matched the ansible icon to files whose source is ansible

At a glance, it seems that `language-ansible` replaces Atom's default YAML grammar, meaning that every single `.yml` file the user opens gets treated like an Ansible file...

Now, I have literally zero understanding of Ansible, what it's used for, why/how it differs from regular YAML, and how to tell the difference between the two filetypes. A config snippet [here](https://github.com/haad/language-Ansible#configcson) suggests that Ansible files can be identified from their path:

~~~cson
"*":
  "file-types":
    ".*.yml$": "source.ansible"
    ".*/group_vars/.*": "source.ansible"
    ".*/host_vars/.*": "source.ansible"
~~~
If that's the case, then we can certainly show the Ansible icon for `.yml` files which fall inside `group_vars/` and `host_vars/` directories.

**Comment by brandonkal** [comment]
Yes, by default, the `language-ansible` clobbers over all YAML files. I have opened an issue with that developer requesting that that not be the default.
In my particular case, I have added this to my `config.cson`
```
core:
    customFileTypes:
      "source.ansible": "ans"
      "source.yaml": "yml"
```
This way I ensure the default YAML grammar is not overriden unless the file type is `.ans`

Ansible is a tool like Chef to remotely provision servers by defining the desired state. Its grammar is mostly vanilla YAML with some small exceptions because the input is parsed by python before parsing the YAML.
So this is valid:
```
- name: Fetch the MySQL backup
    fetch: src=/tmp/wp_backup.sql.tar.gz dest=./backups/ flat=yes
```
Even though the YAML way would be this (also valid):
```
- name: Fetch the MySQL backup
    fetch:
      src: /tmp/wp_backup.sql.tar.gz
      dest: ./backups/
      flat: yes
```

Ansible consists of playbooks which typically exist at the root or in an `ansible` folder. They include other yaml files such as those you mentioned above and also those found in `/roles/*/tasks/*.yml` and `/roles/*/handlers/*.yml` relative to the playbook file location.

## Playbook vs Other Ansible Files

I am using the Atom package `Linter-Ansible-Syntax` which is what requires the `language-ansible` package. It just calls `ansible-playbook playbook_filename --syntax-check`, which only functions on ansible playbooks, not ansible roles, include_files, or variable files. This is one reason why I went with a different file extension for ansible playbook files, so that the linter will not run on the other ansible files, where it would fail.

This is why it may be worth distinguishing between ansible playbook files and other ansible files which could be done by using a different color for the ansible icon.

## Color Suggestion
I would also suggest using a different color for the ansible icon. Ansible files are often found alongside python files (ansible uses python). Because the python icon is blue, a different color would improve visual grepping. I found this color to be look nice:
```
color: #599c84;
```

## Vault files

Another crazy idea: Ansible variable files are often stored in encrypted form so they can be version controlled without exposing deployment secrets. It would be very slick if `file-icons` displayed a lock icon when the file is encrypted. I am not sure if a lock icon exists in the iconset. Encrypted vault files begin with this line:
```
$ANSIBLE_VAULT;1.1;AES256
```
`file-icons` could check for the existence of `$ANSIBLE_VAULT;` in the first line and display a lock icon if the file is in an encrypted state.

**Comment by Alhadis** [comment]
Ah, I see. Thank you for the detailed explanation! 😁

Currently, the logic for mapping icons to files is handled in an unfortunately rigid and unextensible manner. A list of [strategy](https://github.com/file-icons/atom/tree/ca5947b19849824916f5c2309ebe984d223eeef3/lib/service/strategies) objects are tested in a predefined order, and there's little room to implement heuristics (such as the ones you've described).

However, I'm in the process of rethinking the package's file-to-icon mapping strategies, as an infrastructural rehaul was due anyway. So the ideas you've explained may actually become possible, depending on how things pan out. :-)

**Comment by andmos** [comment]
Imagine my joy when suddenly all my Ansible files got the pretty icons over night! Thanks @Alhadis and @brandonkal!
