### ISSUE TITLE
Icons not showing on Mac HighSierra

### ISSUE THREAD

**Issue by ospaarmann** [file-icons/atom#763]
Hi,

Mac iOS 10.13.6
Atom: 1.31.1

all icons are suddenly just little rectangles. It looks like the icon font is not loading correctly.

<img width="223" alt="screen shot 2018-10-07 at 22 51 44" src="https://user-images.githubusercontent.com/308086/46586783-a60a0080-ca83-11e8-9a2b-0c37b5228450.png">

<img width="290" alt="screen shot 2018-10-07 at 22 51 55" src="https://user-images.githubusercontent.com/308086/46586785-adc9a500-ca83-11e8-9ccb-2cc85e1b25a4.png">

I toggled the Developer Tools to see if any requests failed. When reloading the window (via View -> Developer -> Reload Window) I receive a white page with this error (which I cannot copy for some strange reason, so here you go with a screenshot)

<img width="872" alt="screen shot 2018-10-07 at 22 54 29" src="https://user-images.githubusercontent.com/308086/46586816-08630100-ca84-11e8-99aa-4a815994df46.png">

I did not install any new packages. It just stopped working.

**Comment by Alhadis** [comment]
In the developer tools, could you inspect one of the faulty elements to see what styling is being applied? There may be another package or theme which you upgraded to which introduced new (conflicting) styles.

**Comment by ospaarmann** [comment]
@Alhadis the issue disappeared overnight. Restarting Atom a couple of times. I didn't run any updates. So now it is difficult for me to give you any further insights.

I will report back when this issue arises again.

**Comment by Alhadis** [comment]
Alright. I'll close this issue in the meantime, since the causes are inconclusive.

Thanks!
