### ISSUE TITLE
icon changes when execute permission added

### ISSUE THREAD

**Issue by finanalyst** [file-icons/atom#765]
I am writing Perl 6 programs, using Atom on Ubuntu  
Atom with file-icons correctly shows files with extension .p6 and .pm6 with the perl6 icon (a butterfly)  
However, when I give the program execute permission, the file-icon changes to the perl icon (an onion)  

I looked at the wrong icon issue 750, but it does not seem to be the same.

I updated Atom, now running Atom 1.31.2 and file-icons 2.1.25  
I cleared the cache (Ctl-Shift-P file-icons).   

I have changed config.cson to contain
```cson
    customFileTypes:
      'source.perl6fe': [
        'p6'
        'pm6'
        'pm'
        't'
      ]
```
as suggested in the language-perl6 package. The problem continues, viz. *.p6 files with an execute bit are associated with a perl icon.

**Comment by Alhadis** [comment]
That's seriously bizarre. Do any of the files in question have a hashbang like `#!/usr/bin/env perl` or `#! perl`? If not, does toggling the "Hashbang" strategy help? (Under **Package Settings** → `file-icons` → **Strategies**).

I *just* noticed that the pattern for the Perl 5 interpreter is a little too open-ended, matching `#!/perl6` before something like `#!/perl5`. Could you apply the following diff to `~/.atom/packages/file-icons/lib/icons/.icondb.js`, clear the cache, then restart Atom?

~~~diff
diff --git a/lib/icons/.icondb.js b/lib/icons/.icondb.js
index 4bb3772..19f2bcf 100644
--- a/lib/icons/.icondb.js
+++ b/lib/icons/.icondb.js
@@ -1053,7 +1053,7 @@ module.exports = [
 ["icon-file-pdf",["medium-red","medium-red"],/\.pdf$/i,,false,,,,/^%PDF/],
 ["peg-icon",["medium-red","medium-red"],/\.pegjs$/i,,false,/^pegjs$/,/\.pegjs$/i,/^pegjs$/i],
 ["peg-icon",["medium-maroon","medium-maroon"],/\.pegcoffee$/i,,false,/^pegcoffee$/,/\.pegcoffee$/i,/^Peg[\W_ \t]?Js$|^pegc[0o]ffee$/i],
-["perl-icon",["medium-blue","medium-blue"],/\.p(?:er)?l$/i,,false,/^c?perl[\d.]*$/,/\.perl$/i,/^C?Perl$/i],
+["perl-icon",["medium-blue","medium-blue"],/\.p(?:er)?l$/i,,false,/^c?perl5?$/,/\.perl$/i,/^C?Perl$/i],
 ["perl-icon",["dark-blue","dark-blue"],/\.al$|\.pm$/i],
 ["perl-icon",["dark-purple","dark-purple"],/\.ph$/i],
 ["perl-icon",["medium-purple","medium-purple"],/\.plx$/i],
~~~

**Comment by finanalyst** [comment]
Sorry for delay. 
Applied patch, cleared, restarted. This solved the issue for me. Thank you.
