### ISSUE TITLE
Better go-icon

### ISSUE THREAD

**Issue by clafoutis42** [file-icons/atom#767]
Hi !
I'm a golang developper, and honestly think that the gopher would be a better icon for go than the G and O letters.

He looks like this !
![](https://ih1.redbubble.net/image.377846240.0222/ap,550x550,12x16,1,transparent,t.png)

Thanks !

**Comment by Alhadis** [comment]
Hi @clafoutis42,

We used this icon until Go changed their branding (see #728). To bring it back, add the following to your stylesheet:

~~~css
.go-icon:before{
	content: "\e624";
	font-size: 15px;
	left: auto;
	top: 3px;
}
~~~
