### ISSUE TITLE
Special icon for the project folder

### ISSUE THREAD

**Issue by vokyecito** [file-icons/atom#777]
I would like a special icon for the project folder, to identify project folders, from the rest of the folders.

**Comment by Alhadis** [comment]
What sort of project folders are these? Can you post a screenshot of your `tree-view` to show me their names and contents?

There should already be a repository icon appearing if the project is a Git repository. It should look like this:

<img src="https://user-images.githubusercontent.com/2346707/53301277-e2a88e00-38a4-11e9-8274-8b2d43a61c6e.png" width="150" alt="Figure 1" />

**Comment by vokyecito** [comment]
Win10 & Atom

I use the option "add project folder"

![image](https://user-images.githubusercontent.com/47945752/53309803-7e1f0c00-386f-11e9-8e9d-27205a6adae8.png)

**Comment by Alhadis** [comment]
Add the following to [your stylesheet](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks):

~~~less
.project-root-header > .icon::before{
	content: "\f001";
	font-family: "Octicons Regular";
}
~~~

The code assigned to `content:` specifies the icon, and the value of `font-family` determines the icon set. There are many icons to choose from: see the package's [customisation guide](https://github.com/file-icons/atom#customisation).

**Comment by vokyecito** [comment]
Thank you!

![image](https://user-images.githubusercontent.com/47945752/53344330-09cc8300-38d8-11e9-9d2f-a0086dd42dfb.png)
