### ISSUE TITLE
Icons Origin

### ISSUE THREAD

**Issue by JosephTLyons** [file-icons/atom#783]
There's no issue here, I'm just curious where the icons from.  Who creates them and under what sort of licensing?  I've always been curious of this.

**Comment by Alhadis** [comment]
I do. I've been heavily involved in graphic design and multimedia even longer than web development, and whipping together a bunch of Bézier curves is pretty trivial if you've been doing this shit for 15 years. 😂

As for what license, it's the "go nuts, share and enjoy, be happy" license.

**Comment by Alhadis** [comment]
http://vimeo.com/Alhadis There you go. :)

**Comment by JosephTLyons** [comment]
I assumed it was the repo owner, but I wasn't sure.  It seems like it would be a lot of work to have to make one whenever you find there's a file you've missed, but based on the few conversations I've had here in the past, I've come to realize that your work ethic isn't the same as most others (its greater than others).  Very cool that its all "in-house."

**Comment by Alhadis** [comment]
Haha, thanks mate. 😀

**Comment by JosephTLyons** [comment]
No problem.  Its always inspiring checking out a repo containing software that has helped so many people out.  I can't imagine what it must feel like to have a product this successful / widely - used.

**Comment by Alhadis** [comment]
Hey, honest question: how is it people actually like markdown?

Look how [badly-cramped](https://github.com/file-icons/atom/releases/tag/v2.1.32) the icon-previews are in the release notes. It was either that, or having `<p>…</p>` enclose every single list-entry.

Markdown is either the worst fucking markup language on Earth, or the most successful act of IT trolling in history. Either way, I hate it.

**Comment by JosephTLyons** [comment]
Ease of use.  I use it, but don't love it.  But it's definitely easier to use over most of the alternatives it seems.

**Comment by JosephTLyons** [comment]
Those icons are look nice though.

**Comment by Alhadis** [comment]
Thanks. ^_^; I'm actually running out of icons to add, so, [suggestions/requests are welcome](https://github.com/file-icons/source). 😀

**Comment by JosephTLyons** [comment]
I realize that this is totally off-topic and that the problem is pretty ridiculous, but since we have a little dialogue going here and you seem to be the guru of language packages.. I was curious how hard you think it might be to make an "English Language" package?  One that is activated maybe in .txt files or other prose files.  I first saw this here, in [IA Writer](https://ia.net/writer), but it essentially highlights certain words within each sentence (verbs, nouns, etc).  I think this would be pretty difficult, I'm assuming they have some sort of dictionaries they have to search through and such, but I'm not sure.  How challenging of a task would this be?

**Comment by Alhadis** [comment]
With regular expressions and nesting? Literally impossible.

Natural languages and computer languages are both restrained by the rules set down by grammar and syntax, but any similarities stop there. You're better off feeding a neural network a corpora of written material and teaching it to recognise human language (which… is literally how every search engine actually works nowadays).

**Comment by JosephTLyons** [comment]
Thanks for the response.  I only recently got into regex not long ago, but have very limited experience with it.  Even though I’ve been forced to take some super hairy courses in my degree and I’m 1 week away from graduating, I’ve seemed to somehow miss out on many every day programming tools use frequently, such as Regex.  Probably the byproduct of using only C-based languages.

At any rate, now I know to avoid this sort of thing when fiddling around with summer projects.

**Comment by Alhadis** [comment]
One of my favourite quotes comes from [Donald Knuth](https://en.wikipedia.org/wiki/Donald_Knuth):

> "Science is what we know well enough to teach to a computer. Art is everything else we do."

I'm of the belief that some things are best left to humans, not circuitry. =) Quality control (artwork, documentation, design, etc) and human language are two things I'd never trust to a computer.

Anyway. I recommend digging into Perl if this area of linguistics interests you. Its creators were linguists: Larry Wall even took influences from English when designing Perl's syntax. When you realise how balls-numbingly hard it is to learn, you'll understand why natural and computer languages are best kept worlds apart. 😜

(This is coming from a Perl programmer. Trust me, the language is NOT friendly to those coming from C or Java...)

**Comment by JosephTLyons** [comment]
Love Knuth.  Collect his books actually, although I’d be lying if I said I understood a majority of even one of his books (I’m decent in mathematics, but not Donald Knuth decent).

As for Perl, I’m familiar with it.  One of the classes I took required us to do some simple assigment, to make some tool that automatically generated HTML websites, but it was in Perl.  That was enough for me and I never looked back! Lol.
