### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by skadevz** [file-icons/atom#785]
$ apm install file-icons   
Installing file-icons to /home/skadevz/.atom/packages ✗

npm ERR! Unexpected end of JSON input while parsing near '...5KqhjXJ3vvf+WhaOU8/cT'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/skadevz/.atom/.apm/_logs/2019-05-06T12_06_31_684Z-debug.log

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/share/atom/resources/app/apm/bin/node',
1 verbose cli   '/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/home/skadevz/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/home/skadevz/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/file-icons/versions/2.1.32/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.18',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 2ef04b704bb3a8ed
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/file-icons/versions/2.1.32/tarball 13180ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/file-icons/versions/2.1.32/tarball fetched in 13203ms
9 timing stage:loadCurrentTree Completed in 13364ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule file-icons@2.1.32 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/lru-cache 8ms (from cache)
18 silly pacote range manifest for lru-cache@^5.1.1 fetched in 95ms
19 silly resolveWithNewModule lru-cache@5.1.1 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/mapped-disposable 414ms (from cache)
21 silly pacote range manifest for mapped-disposable@^1.0.3 fetched in 475ms
22 silly resolveWithNewModule mapped-disposable@1.0.3 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/micromatch 480ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/atom-fs 485ms (from cache)
25 silly pacote range manifest for micromatch@^3.1.10 fetched in 581ms
26 silly resolveWithNewModule micromatch@3.1.10 checking installable status
27 silly pacote version manifest for atom-fs@v0.1.6 fetched in 617ms
28 silly resolveWithNewModule atom-fs@0.1.6 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/yallist 189ms (from cache)
30 silly pacote range manifest for yallist@^3.0.2 fetched in 271ms
31 silly resolveWithNewModule yallist@3.0.3 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/extend-shallow 221ms (from cache)
33 http fetch GET 304 https://registry.npmjs.org/array-unique 235ms (from cache)
34 http fetch GET 304 https://registry.npmjs.org/fragment-cache 235ms (from cache)
35 silly pacote range manifest for extend-shallow@^3.0.2 fetched in 263ms
36 silly resolveWithNewModule extend-shallow@3.0.2 checking installable status
37 silly pacote range manifest for fragment-cache@^0.2.1 fetched in 265ms
38 silly resolveWithNewModule fragment-cache@0.2.1 checking installable status
39 http fetch GET 304 https://registry.npmjs.org/nanomatch 290ms (from cache)
40 silly pacote range manifest for array-unique@^0.3.2 fetched in 302ms
41 silly resolveWithNewModule array-unique@0.3.2 checking installable status
42 silly pacote range manifest for nanomatch@^1.2.9 fetched in 347ms
43 silly resolveWithNewModule nanomatch@1.2.13 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/arr-diff 388ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/object.pick 385ms (from cache)
46 silly pacote range manifest for arr-diff@^4.0.0 fetched in 390ms
47 silly resolveWithNewModule arr-diff@4.0.0 checking installable status
48 http fetch GET 304 https://registry.npmjs.org/extglob 389ms (from cache)
49 silly pacote range manifest for object.pick@^1.3.0 fetched in 389ms
50 silly resolveWithNewModule object.pick@1.3.0 checking installable status
51 silly pacote range manifest for extglob@^2.0.4 fetched in 393ms
52 silly resolveWithNewModule extglob@2.0.4 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/define-property 397ms (from cache)
54 silly pacote range manifest for define-property@^2.0.2 fetched in 399ms
55 silly resolveWithNewModule define-property@2.0.2 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/kind-of 398ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/braces 401ms (from cache)
58 silly pacote range manifest for kind-of@^6.0.2 fetched in 402ms
59 silly resolveWithNewModule kind-of@6.0.2 checking installable status
60 silly pacote range manifest for braces@^2.3.1 fetched in 404ms
61 silly resolveWithNewModule braces@2.3.2 checking installable status
62 http fetch GET 304 https://registry.npmjs.org/regex-not 186ms (from cache)
63 http fetch GET 304 https://registry.npmjs.org/snapdragon 187ms (from cache)
64 silly pacote range manifest for regex-not@^1.0.0 fetched in 190ms
65 silly resolveWithNewModule regex-not@1.0.2 checking installable status
66 silly pacote range manifest for snapdragon@^0.8.1 fetched in 190ms
67 silly resolveWithNewModule snapdragon@0.8.2 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/to-regex 243ms (from cache)
69 silly pacote range manifest for to-regex@^3.0.2 fetched in 296ms
70 silly resolveWithNewModule to-regex@3.0.2 checking installable status
71 silly pacote range manifest for extend-shallow@^2.0.1 fetched in 31ms
72 silly resolveWithNewModule extend-shallow@2.0.1 checking installable status
73 http fetch GET 304 https://registry.npmjs.org/arr-flatten 139ms (from cache)
74 http fetch GET 304 https://registry.npmjs.org/snapdragon-node 140ms (from cache)
75 http fetch GET 304 https://registry.npmjs.org/fill-range 165ms (from cache)
76 silly fetchPackageMetaData error for fill-range@^4.0.0 Unexpected end of JSON input while parsing near '...5KqhjXJ3vvf+WhaOU8/cT'
77 silly pacote range manifest for arr-flatten@^1.1.0 fetched in 170ms
78 silly resolveWithNewModule arr-flatten@1.1.0 checking installable status
79 silly pacote range manifest for snapdragon-node@^2.0.1 fetched in 169ms
80 silly resolveWithNewModule snapdragon-node@2.1.1 checking installable status
81 http fetch GET 304 https://registry.npmjs.org/repeat-element 172ms (from cache)
82 http fetch GET 304 https://registry.npmjs.org/isobject 174ms (from cache)
83 http fetch GET 304 https://registry.npmjs.org/split-string 174ms (from cache)
84 silly pacote range manifest for isobject@^3.0.1 fetched in 176ms
85 silly resolveWithNewModule isobject@3.0.1 checking installable status
86 silly pacote range manifest for split-string@^3.0.2 fetched in 176ms
87 silly resolveWithNewModule split-string@3.1.0 checking installable status
88 silly pacote range manifest for repeat-element@^1.1.2 fetched in 191ms
89 silly resolveWithNewModule repeat-element@1.1.3 checking installable status
90 timing stage:rollbackFailedOptional Completed in 1ms
91 timing stage:runTopLevelLifecycles Completed in 15074ms
92 silly saveTree apm-install-dir-11946-28384-18mo6fu.057i
92 silly saveTree └─┬ file-icons@2.1.32
92 silly saveTree   ├─┬ atom-fs@0.1.6
92 silly saveTree   │ └── mapped-disposable@1.0.3
92 silly saveTree   ├─┬ lru-cache@5.1.1
92 silly saveTree   │ └── yallist@3.0.3
92 silly saveTree   ├── mapped-disposable@1.0.3
92 silly saveTree   └─┬ micromatch@3.1.10
92 silly saveTree     ├── arr-diff@4.0.0
92 silly saveTree     ├── array-unique@0.3.2
92 silly saveTree     ├─┬ braces@2.3.2
92 silly saveTree     │ ├── arr-flatten@1.1.0
92 silly saveTree     │ ├── extend-shallow@2.0.1
92 silly saveTree     │ ├── isobject@3.0.1
92 silly saveTree     │ ├── repeat-element@1.1.3
92 silly saveTree     │ ├── snapdragon-node@2.1.1
92 silly saveTree     │ ├── snapdragon@0.8.2
92 silly saveTree     │ ├─┬ split-string@3.1.0
92 silly saveTree     │ │ └── extend-shallow@3.0.2
92 silly saveTree     │ └─┬ to-regex@3.0.2
92 silly saveTree     │   ├── define-property@2.0.2
92 silly saveTree     │   └── regex-not@1.0.2
92 silly saveTree     ├── define-property@2.0.2
92 silly saveTree     ├── extend-shallow@3.0.2
92 silly saveTree     ├─┬ extglob@2.0.4
92 silly saveTree     │ └── fragment-cache@0.2.1
92 silly saveTree     ├── fragment-cache@0.2.1
92 silly saveTree     ├── kind-of@6.0.2
92 silly saveTree     ├─┬ nanomatch@1.2.13
92 silly saveTree     │ └── object.pick@1.3.0
92 silly saveTree     ├── object.pick@1.3.0
92 silly saveTree     ├── regex-not@1.0.2
92 silly saveTree     ├── snapdragon@0.8.2
92 silly saveTree     └── to-regex@3.0.2
93 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...5KqhjXJ3vvf+WhaOU8/cT'
93 verbose stack     at JSON.parse (<anonymous>)
93 verbose stack     at parseJson (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
93 verbose stack     at consumeBody.call.then.buffer (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
93 verbose stack     at <anonymous>
93 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
94 verbose cwd /tmp/apm-install-dir-11946-28384-18mo6fu.057i
95 verbose Linux 4.15.0-48-generic
96 verbose argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/skadevz/.atom/.apm/.apmrc" "--userconfig" "/home/skadevz/.atom/.apmrc" "install" "https://www.atom.io/api/packages/file-icons/versions/2.1.32/tarball" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
97 verbose node v8.9.3
98 verbose npm  v6.2.0
99 error Unexpected end of JSON input while parsing near '...5KqhjXJ3vvf+WhaOU8/cT'
100 verbose exit [ 1, true ]

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 2.7.15rc1
git 2.17.1

I didn't use proxy, the internet connection is stable.
How to fix it?

**Comment by Alhadis** [comment]
Try installing with `apm install --production file-icons`, which omits the `devDependencies` from the install.

If it happens again, wipe the cache (`rm -rf ~/.atom/.apm`) and rerun the command.

Sometimes installations fail with weird errors like this one, usually because a CDN server had a hiccup. It's not something we can control, really.

**Comment by Alhadis** [comment]
Closing this as it isn't a package-related issue. Let me know if you have any further questions, however.

**Comment by skadevz** [comment]
So everything that I need to do is clear the cache. Thanks, it works!
