### ISSUE TITLE
add icon for requirements.txt

### ISSUE THREAD

**Issue by LeonardoFurtado** [file-icons/atom#792]
Can you add an icon for the requirements.txt file? This is a very common file in Python projects, which is used to put the libraries needed to run the software.

**Comment by Alhadis** [comment]
No, sorry. There's too high a risk of assigning the wrong icon to a file which happens to be named `requirements.txt` (that isn't in a Python project).

However, you can [use your stylesheet](https://github.com/file-icons/atom#assign-icons-by-file-extension) to add an icon to these files, if you prefer:

~~~css
.icon[data-name="requirements.txt"]:before{
	content: "\f076";
	font-family: "Octicons Regular";
	font-size: 17px;
	left: 1px;
	top: 1px;
}
~~~

The above example adds the [checklist icon](https://github.com/file-icons/atom/blob/727068c023c4c09f004289903510164f5efc24a9/styles/icons.less#L51); feel free to experiment.

**Comment by LeonardoFurtado** [comment]
> No, sorry. There's too high a risk of assigning the wrong icon to a file which happens to be named `requirements.txt` (that isn't in a Python project).
> 
> However, you can [use your stylesheet](https://github.com/file-icons/atom#assign-icons-by-file-extension) to add an icon to these files, if you prefer:
> 
> ```css
> .icon[data-name="requirements.txt"]:before{
> 	content: "\f076";
> 	font-family: "Octicons Regular";
> 	font-size: 17px;
> 	left: 1px;
> 	top: 1px;
> }
> ```
> 
> The above example adds the [checklist icon](https://github.com/file-icons/atom/blob/727068c023c4c09f004289903510164f5efc24a9/styles/icons.less#L51); feel free to experiment.

I'll try it. Thanks <3
