### ISSUE TITLE
Add .ds icon style

### ISSUE THREAD

**Issue by matteobertoldo** [file-icons/atom#794]
Hi man! 👋

It's possible to associate the icon for `.ds` files?.
Here an official Salesforce B2C [documentation](https://documentation.b2c.commercecloud.salesforce.com/DOC2/index.jsp?topic=%2Fcom.demandware.dochelp%2FScriptProgramming%2FUsingJavascriptmodules.html&resultof=%22%64%73%22%20).

> "What is a B2C Commerce Script Module?
> 
> A CommonJS-compliant B2C Commerce script module is either a script file (with a `.js`, `.json`, or **`.ds`** extension) or a directory containing script files. A module can hide private data, while exposing public objects and methods via a free variable named exports."

#### Proposal icon

Icon for `.js` files but in light blue as for `.jsx` files, given the Salesforce blue 😅.

Thanks!

**Comment by Alhadis** [comment]
Hey there,

You can achieve this with your stylesheet:

~~~less
.icon[data-name$=".ds"]::before{
	font: 14px Mfizz;
	content: "\f129";
	top: 1px;
	
	body:not(.file-icons-colourless) &{
		color: #00a1e0;
	}
}
~~~

There appear to be a number of filetypes which use the `.ds` extension, so I'm not sure adding the JS icon indiscriminately would be a good idea. 🤔

**Comment by matteobertoldo** [comment]
Thank you so much for the style snippet! Very nice now! 😝. 
I only updated the hex to agree with the default blue. I added the hexadecimal of the `.medium-blue` class (`#6a9fb5`) as I meant on the first comment. Here is the result. Identical to the color of `ISML` files for Salesfoce projects.

<img width="787" alt="hero-tab" src="https://user-images.githubusercontent.com/15775323/71183665-abaec900-2278-11ea-9662-8c665a418734.png">

> There appear to be a number of filetypes which use the .ds extension, so I'm not sure adding the JS icon indiscriminately would be a good idea. 🤔

Aaaah, I guess! You'r right! I don't think it is correct to always insert the `js` icon.
I haven't investigated your code, but maybe you can target the icon if the file is present in a certain directory?. I've been working for about 3 years with SFCC projects and I've always seen the files with the extension `.ds` allocated to the path: `**/cartridge/scripts/**/index.ds`. Here an example:

<img width="243" alt="hero-tree-view" src="https://user-images.githubusercontent.com/15775323/71183812-f03a6480-2278-11ea-9b49-617b346eb8b9.png">

**Comment by Alhadis** [comment]
> I've been working for about 3 years with SFCC projects and I've always seen the files with the extension .ds allocated to the path: `**/cartridge/scripts/**/index.ds`.

I'll take your word for it. 😉 I've added a rule that will target `.ds` files located within `/cartridge/scripts/*` directories. You should see it in the next release. 👍
