### ISSUE TITLE
Squirrel extension

### ISSUE THREAD

**Issue by Wanty5883** [file-icons/atom#800]
`.gnut` files are also an extension of Squirrel files. Would be nice to add 👍 

For the future should I create an issue every times, or I can add comment to one I already created ?
Maybe you can create one and leave it open ? So people can add comment for this purpose ?

**Comment by Alhadis** [comment]
Fixed. Sorry for the delay, I had to fix the CI script because of a regression upstream.

> Maybe you can create one and leave it open ? So people can add comment for this purpose ?

I'd rather people submit separate issues or pull-requests. It's easier to keep track of that way.
