### ISSUE TITLE
Failed when update to 2.1.39

### ISSUE THREAD

**Issue by yogs22** [file-icons/atom#801]
Hi! i got error message when i update file icon version to 2.1.39, this is the detail of error :

![image](https://user-images.githubusercontent.com/25165999/74288720-b8730900-4d5f-11ea-9b4c-1a337b6256a0.png)

**Comment by Alhadis** [comment]
Follow [these steps](https://github.com/file-icons/atom/blob/master/README.md#installation-halts-with-an-npm-error) and restart Atom.
