### ISSUE TITLE
Upgrade to 2.1.38 Error

### ISSUE THREAD

**Issue by yogs22** [file-icons/atom#802]
Hello, i was trying to clear file icon cache and reupdate the package, but i still got an error

![image](https://user-images.githubusercontent.com/25165999/75125097-f23ffa00-56e5-11ea-9ef3-5e033a4d2a8f.png)

**Comment by Alhadis** [comment]
Have you completed [these steps](https://github.com/file-icons/atom#installation-halts-with-an-npm-error)?

**Comment by Alhadis** [comment]
Wipe the contents of `~/.atom/.apm` and try again. The `unexpected end of file` error indicates an incomplete download, which can happen when `atom.io`'s servers time-out during an update. 

In other words, it's nothing to do with `file-icons`, and everything to do with Atom's package registry (and by extension, `apm` itself).
