### ISSUE TITLE
Nonexistent `file-icons:clear-cache` command

### ISSUE THREAD

**Issue by AlexWayfer** [file-icons/atom#807]
![image](https://user-images.githubusercontent.com/6510020/78128534-c4ee1680-741e-11ea-9eef-60b961ac0856.png)

`2.1.40`

**Comment by Alhadis** [comment]
More context, please. Have you installed and activated the package? Or did you upgrade the package but haven't restarted Atom yet?

**Comment by AlexWayfer** [comment]
> Have you installed and activated the package?

I'm using this package for a long time. Today I've noticed #808, go to README, found info about `clear-cache` command and didn't find it in commands panel.

> Or did you upgrade the package but haven't restarted Atom yet?

I think, there was auto-update of package, yes. And I've restarted Atom. And I've installed Atom binary. Nothing changed.

I see errors in DevTools, but not in Atom UI:

```
internal/process/warning.js:18 (node:87365) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
writeOut @ internal/process/warning.js:18
output @ internal/process/warning.js:69
process.on @ internal/process/warning.js:100
emit @ events.js:182
(anonymous) @ internal/process/warning.js:74
_tickCallback @ internal/process/next_tick.js:61

styles-element.coffee:62 GET file:///usr/share/atom/resources/app.asar/static/ui-variables net::ERR_FILE_NOT_FOUND
  | StylesElement.styleElementAdded | @ | styles-element.coffee:62
-- | -- | -- | --
  | simpleDispatch | @ | <embedded>:11
  | emit | @ | <embedded>:11
  | addStyleElement | @ | <embedded>:11
  | addStyleSheet | @ | <embedded>:11
  | activateStylesheets | @ | <embedded>:11
  | activateNow | @ | <embedded>:11
  | measure | @ | <embedded>:11
  | measure | @ | <embedded>:11
  | activationPromise.activationPromise.Promise | @ | <embedded>:11
  | activate | @ | <embedded>:11
  | activatePackage | @ | <embedded>:11
  | config.transactAsync | @ | <embedded>:11
  | transactAsync | @ | <embedded>:11
  | activatePackages | @ | <embedded>:11
  | activate | @ | <embedded>:11
  | t.loadState.then | @ | <embedded>:1
  | async function (async) |   |  
  | t.loadState.then | @ | <embedded>:1
  | Promise.then (async) |   |  
  | startEditorWindow | @ | <embedded>:1
  | t.exports | @ | <embedded>:1
  | setupWindow | @ | index.js:175
  | window.onload | @ | index.js:106
  | load (async) |   |  
  | (anonymous) | @ | index.js:23
  | (anonymous) | @ | index.js:217


```

**Comment by AlexWayfer** [comment]
`file-icons` package is activated, I see no errors of it and can configure:

![image](https://user-images.githubusercontent.com/6510020/78129519-69248d00-7420-11ea-98e1-85fb795cd6cd.png)

**Comment by Alhadis** [comment]
Does searching for `clear cache` throw up any results?

**Comment by AlexWayfer** [comment]
> Does searching for `clear cache` throw up any results?

Not relevant, I think:

![image](https://user-images.githubusercontent.com/6510020/78130143-6a09ee80-7421-11ea-9669-dd9a6a3178cb.png)

**Comment by AlexWayfer** [comment]
Re-installation via `apm` resolved this issue too: https://github.com/file-icons/atom/issues/808#issuecomment-607189747

**Comment by Alhadis** [comment]
Glad to hear. Let me know if you continue to have troubles.
