### ISSUE TITLE
Missing almost all icons

### ISSUE THREAD

**Issue by AlexWayfer** [file-icons/atom#808]
![image](https://user-images.githubusercontent.com/6510020/78129075-adfbf400-741f-11ea-90e3-c98e910e9b78.png)

* file-icons 2.1.40
* Atom 1.45.0
* Arch Linux
* Node.js 13.12.0

**Comment by Alhadis** [comment]
Okay, it looks like your package didn't finish downloading before Atom "installed" it. Could you Quit Atom and then run the following commands, please?

~~~shell
rm -rf ~/.atom/.apm ~/.atom/packages/file-icons
apm install --production file-icons
~~~

Provided `apm` doesn't shit the bed, you should see `file-icons` behave normally the next time you boot Atom.

**Comment by AlexWayfer** [comment]
Of course.

I've ran only `apm install file-icons` and it resolves all issues. Thank you, and sorry for bothering.
