### ISSUE TITLE
Add icon to "client" folder

### ISSUE THREAD

**Issue by sidelong44** [file-icons/atom#811]
In my folder structure, the list of "client", "server", "shared" really lacks an icon only for the folder "client". Add it, please! 🙏🙏🙏
I think that many people like to name folders for client source files...

**Comment by Alhadis** [comment]
Far too generic. Isn't there an existing icon you can use?

**Comment by sidelong44** [comment]
No, the directory with source files for the client part of web app should be named "client", this is logical.
I can not give it another title, because there is no more accurate and concise word.

Sorry for the long answer. This issue is still relevant.

**Comment by Alhadis** [comment]
What icon are you expecting to see, exactly?

**Comment by sidelong44** [comment]
Anything to your taste.
I'm just pleased to see when all directories have their own icon.
Alternatively, you can try the user icon 👤 or something else.
I would be happy to see any implementation 🙃😊

**Comment by Alhadis** [comment]
We don't have icons assigned to `server` or `shared` directories, what exactly are you using?

**Comment by sidelong44** [comment]
I'm using WebStorm with the Atom Material Icons plugin.
![image](https://user-images.githubusercontent.com/40847213/80579663-16d08f00-8a13-11ea-9d54-5095802dd9f6.png)

**Comment by sidelong44** [comment]
Oh, for sure, there is a separate repository for this.
@Alhadis, sorry to bother you)
