### ISSUE TITLE
Incorrect icons (Jupyter and Julia notebooks)

### ISSUE THREAD

**Issue by domiden** [file-icons/atom#813]
First at all, many thanks for your hard work. I'm in the process to get familiar with atom editor and its flexibility.  I was amazed when I found your package! Unfortunately, no appropriate icons are shown for **Jupyter** (`.ipynb`) and **Julia** (markdown-based) notebook (`.jmd`).  It would be brilliant if you guys could integrate it. Btw. be aware that Jupyter notebook are able to support different kernels. Thanks again!

<img width="146" alt="Screenshot 2020-04-30 at 13 38 34" src="https://user-images.githubusercontent.com/24540355/80706703-0985d400-8ae9-11ea-9397-a0cce283ef64.png">

**Comment by Alhadis** [comment]
I'll add the markdown icon to `.jmd`, but we already have [an icon](https://github.com/file-icons/icons/blob/master/svg/Jupyter.svg) assigned to Jupyter Notebooks.

Moreover, that's not the icon we use for `.html` files. Do you have another icon package installed on top of this one? If so, that's going to cause conflicts.

**Comment by domiden** [comment]
Sorry, was the wrong screenshot, therefore partly wrong conclusion. 

<img width="142" alt="Screenshot 2020-04-30 at 14 44 40" src="https://user-images.githubusercontent.com/24540355/80711971-82892980-8af1-11ea-9982-397ac7a7e588.png">
