### ISSUE TITLE
Update file icons

### ISSUE THREAD

**Issue by ThatXliner** [file-icons/atom#830]
I noticed that the file-icons/icons repository is getting more updated while this repo (and the file-icons/vs-code repo) isn't receiving the updates/added icons. I think the icons folder should be a git submodule to the file-icons/icons icons folder. That way, we can get updated icons every time via `git update submodules` or something like that.

And if the icons aren't going to be releasing frequently, can you post a release schedule?

**Comment by Alhadis** [comment]
It's not that simple. For a start, I'm not sure Atom's package manager even supports submodules (and I'd rather not publish a dummy release somewhere with the express intention of finding out).

Secondly, the [icon-font](https://github.com/file-icons/icons/blob/e057441eb80b1ecbdee8eca3f95bb2a2a0315f54/dist/file-icons.woff2) needs to be regenerated manually, which I do prior to cutting a release.

Finally, each time the font is regenerated, it's another ~196 KBs added to the icon-repository's object store. Hence why releases aren't cut periodically, but on the basis of how many additions there are (either to the font or to the package's list of filetypes).

**Comment by ThatXliner** [comment]
What about a release schedule?

**Comment by Alhadis** [comment]
There's no fixed schedule, but usually a new release happens every 1.5-2 months.

**Comment by Alhadis** [comment]
[There you go](https://github.com/file-icons/atom/releases/tag/v2.1.44), please enjoy. 👍
