### ISSUE TITLE
Add variants for lint-staged config file

### ISSUE THREAD

**Issue by ajotaos** [file-icons/atom#832]
Could this add the other variants for .lintstagedrc that are supported? https://www.npmjs.com/package/lint-staged#configuration

**Comment by Alhadis** [comment]
They're already supported. `lint-staged` doesn't have an icon of its own: the gear icon you're seeing for `.lintstagedrc` files is more-or-less a fallback for every file that starts with a dot.

If you want the gear icon to be shown for the other formats as well, add this to your stylesheet:

~~~less
.icon[data-name="lint-staged.config.js"],
.icon[data-name^=".lintstagedrc"]{
	&[data-name$=".json"],
	&[data-name$=".yaml"],
	&[data-name$=".yml"],
	&[data-name$=".js"],
	&[data-name$=".cjs"]{
		&::before{
			content: "\f02f";
			font: 16px "Octicons Regular";
			top: 1px;
		}
	}
}
~~~

**Comment by ajotaos** [comment]
Just noticed this is the Atom repo, I’m sorry. Should I add this issue in the VS Code repo? I’m trying it .lintstagedrc.json and it displays the cyan json circle.
