### ISSUE TITLE
ReScript: .res extension is missing

### ISSUE THREAD

**Issue by alexfedoseev** [file-icons/atom#834]
I'm not sure if it's done on purpose to avoid clashes, but ReScript's `.res` extension is missing here:
https://github.com/file-icons/atom/blob/master/lib/icons/.icondb.js#L1584

**Comment by Alhadis** [comment]
It was to avoid clashes. However, you can remap the icon using your stylesheet or `config.json` (latter shown below):

~~~cson
"*":
	core:
		customFileTypes:
			"source.rescript": [
				"res"
			]
~~~

**Comment by alexfedoseev** [comment]
Gotcha, thanks!
