### ISSUE TITLE
Unexpected end-of-file error when updating

### ISSUE THREAD

**Issue by deciorf** [file-icons/atom#835]
Updating to “file-icons@2.1.44” failed.Hide output…

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<user>/.atom/.apm/_logs/2020-11-05T12_15_33_464Z-debug.log

**Comment by Alhadis** [comment]
That just means `atom.io`'s servers timed out as you were downloading the update. Follow the steps [given here](https://github.com/file-icons/atom#installation-halts-with-an-npm-error) and try again.

**Comment by deciorf** [comment]
Thank you very much. I was able to upgrade perfectly.
