### ISSUE TITLE
Opening and closing multiple files in webstorm seem to refresh icons and open last closed file

### ISSUE THREAD

**Issue by mattgek** [file-icons/atom#839]
When I open multiple files and close them with cmd+w and unfold the folded directories, the last open file is automatically reopened. I need auto scroll to and from source in Webstorm, because we have a large monorepo and this is a needed feature so disable the feature is no option.

When I disable the plugin and use the default Webstorm icon set, the issue is not present anymore.
I've been in contact with the webstorm team.
The issue is represented in the attached mov file.

https://user-images.githubusercontent.com/17617446/104054844-1f0dda80-51ee-11eb-9825-fe39a9217566.mov

**Comment by Alhadis** [comment]
You're in the wrong place. This is the repository for the [Atom](https://atom.io/) version of File-Icons; no (official) port of it exists for WebStorm.

You're should file this report to whoever maintains the WebStorm port.
