### ISSUE TITLE
How do other folders use the default icon?

### ISSUE THREAD

**Issue by hjzCy** [file-icons/atom#852]
I created a folder called inc.
I want this folder to have the same icon as [folder name: `include`], how do I set it?

**Comment by Alhadis** [comment]
> I want this folder to have the same icon as [folder name: include]

I'm not sure what you mean by that. Could you elaborate? Possibly with a screenshot?

> how do I set it?

All icon customisation is achieved [using CSS](https://github.com/file-icons/atom#examples). To replicate the default styling applied to directories, you'd use:

~~~less
.directory > .header > .icon{
	&[data-name="inc"]:before{
		font-family: "Octicons Regular";
		font-size: 16px;
		content: "\f016";
	}
}
~~~

**Comment by hjzCy** [comment]
简单来说，我希望这两个文件夹的图标相同。

![image](https://user-images.githubusercontent.com/39392770/126742153-cd6778d2-1228-453e-9d6b-42ea263331e2.png)

**Comment by Alhadis** [comment]
I don't know, because the IDEA port isn't something I have control over. You're better off reporting this to the proper repository. 😉

Closing as unrelated.
