### ISSUE TITLE
icon request: `abscracts` folder

### ISSUE THREAD

**Issue by Sigmanificient** [file-icons/atom#858]
When using a [7-1](https://pjmcdermott92.medium.com/the-7-1-scss-architecture-430c50b1f35a) architecture with [scss](https://sass-lang.com) the `abstracts` folder doesn't have any icon. 7-1 architecture is very common in scss.
![image](https://user-images.githubusercontent.com/53050011/135781144-693ee9cb-e3f7-4929-84aa-26d5a0f0c079.png)

[Reference link](https://github.com/Yohann-Boniface-School/Symfony_web/tree/master/public/scss)

Hope that could be fixed!

**Comment by Alhadis** [comment]
Those directory icons aren't ours. Are you using a port of File-Icons for an editor that *isn't* Atom or VS Code?

In any case, we don't add icons for generic directory names, as they have a very high chance of showing up in unrelated contexts (which looks particularly jarring).
