### ISSUE TITLE
Improvement: change python icon

### ISSUE THREAD

**Issue by harmin-parra** [file-icons/atom#866]
Is it possible to change the python icon ?

Something like this [(https://www.iconfinder.com/icons/4518857/python_icon)](https://www.iconfinder.com/icons/4518857/python_icon) with the standard yellow and blue colors that are so characteristic to python.

The current opaque plain blue-gray python icon of this atom extension is not beautiful.

**Comment by Alhadis** [comment]
No, it isn't possible.

A limitation/feature of icon-fonts is that icons are limited to single-colour, solid-filled graphics; i.e., silhouettes. If you want a multicoloured icon, you can use your stylesheet:

~~~less
.python-icon::before{
	content: "";
	width: 16px !important;
	height: 16px !important;
	text-indent: -9999px;
	text-align: left !important;
	vertical-align: text-bottom;
	background: no-repeat 50% 50% url("/path/to/python-icon.png");
	background-size: contain;
}
~~~
