### ISSUE TITLE
Godot: new gdshader extension

### ISSUE THREAD

**Issue by rakkarage** [file-icons/atom#867]
https://github.com/file-icons/atom/issues/806

thanks for the godot support, looks great
shader already has a nice icon but godot is changing its shader extendion in 4.0 to gdshader
possible to make *.gdshader behave like *.shader please and thanks?

**Comment by Alhadis** [comment]
Added in 8707367eb029f1d7ce0a73f03e91957f2599634d; you'll see it in the next release (once I get around to cutting it).
