### ISSUE TITLE
Can't be downloaded and gives error

### ISSUE THREAD

**Issue by Abualhija** [file-icons/atom#869]
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/file-icons/versions/2.1.47/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\.atom\.apm\_logs\2022-04-19T17_00_30_900Z-debug.log

**Comment by Alhadis** [comment]
This has nothing to do with `file-icons` and everything to do with a failed connection to Atom's package registry. Try installing again.

If you're still having trouble (re)installing `file-icons`, open `%HOMEPATH%\.atom` and delete the following directories (if they exist):

* `.apm`
* `packages\file-icons`

**Comment by Abualhija** [comment]
Yes, yesterday everything was back to normal.

Thank you.
