### ISSUE TITLE
Some folders has black filling. Is it a bug?

### ISSUE THREAD

**Issue by max-prtsr** [file-icons/atom#871]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/84035280/171319205-a24c1bd1-f26d-4fd5-8dc7-e49cb94613b0.png">

If not a bug then how to disable it?

UPD: Looks like folder is not filled if I have a file opened somewhere down in it. 
Can it be disabled?

**Comment by Alhadis** [comment]
Hey mate,

Are you using VSCode or Atom? You've opened this issue at the repository for the Atom version of `file-icons`, but your screenshots suggest VSCode.

In either case, it appears that those folders are being colourised by another package/extension you have installed (or in VSCode's case, remnants of the default styling).

**Comment by max-prtsr** [comment]
@Alhadis I'm using IDEA :) Wrong repo to ask?

**Comment by Alhadis** [comment]
Indeed, wrong repository. You want [`mallowigi/a-file-icon-idea`](https://github.com/mallowigi/a-file-icon-idea). 😉

Closing this as it isn't an issue related to an official `file-icons` port.
