### ISSUE TITLE
Java Icon not shown

### ISSUE THREAD

**Issue by meski17** [file-icons/atom#874]
Hey, I'm using the plugin in IntelliJ and the java icon is not displayed. Do you guys know what the problem is? Because the other icons are fine.
![image](https://user-images.githubusercontent.com/30213495/185235372-49496ea1-2029-4035-a86c-aee3642a5b59.png)

**Comment by Alhadis** [comment]
Wrong repository. You appear to be using the IntellJ port of File Icons, which has nothing to do with this project (only Atom and VSCode are officially supported as of this writing).

You should instead submit this to [`mallowigi/a-file-icon-idea`](https://github.com/mallowigi/a-file-icon-idea).
